### ISSUE TITLE
Delete on external table

### ISSUE THREAD

**Issue by Et3rnal** [akveo/ng2-smart-table#1012]
How can I remove a row when using the table in ``mode:'external'`` ?
Ideally, I want to remove a specific row by passing an id or so?

**Comment by perdomofranklin93** [comment]
Same question Et3rnal.

**Comment by Et3rnal** [comment]
@perdomofranklin93 I have done it, however not sure if my case will help you

Have a look here
[https://stackblitz.com/edit/dynamically-row-components-for-smart-table](https://stackblitz.com/edit/dynamically-row-components-for-smart-table)
