### ISSUE TITLE
Page Size

### ISSUE THREAD

**Issue by 602991** [akveo/ng2-smart-table#102]
I need page size dropdown menu, based on selection grid should be update. Kindly let me know how to implement ?

**Comment by neo4u** [comment]
Were you able to implement this? Could you let me know how you managed to implement it?

**Comment by sourabhdeep** [comment]
I found a workaround:
<div class="form-group">
                <label class="col-md-2 col-sm-2 col-xs-12">Per Page</label>
                <div class="col-md-3 col-sm-3 col-xs-10">
                    <select class="form-control" [ngModel]="pageSize" (ngModelChange)="loadNewPageSize($event);">
                        <option *ngFor="let size of pageSizeOptions" value={{size.value}}>
                            {{size.text}}
                        </option>
                    </select>
                </div>
            </div>  
home.componenet.ts

 loadNewPageSize = (newValue: any) => {
        this.getGridData();
        

        this.intermediateSettings = {
            noDataMessage: 'No data found.',
            pager: {
                display: true,
                perPage: newValue
            },
            actions: false,
            columns: {
                TransactionNumber: {
                    title: 'Transaction Number', filter: false
                },
                Status: {
                    title: 'Status', filter: false,
                },
                CreatedBy: {
                    title: 'Created By', filter: false
                },
                CreatedOn: {
                    title: 'Created On', filter: false,
                },
                Product: {
                    title: 'Product'
                },
            },
        };
        //this.settings = Object.assign({}, this.intermediateSettings);
        this.settings = { ...{}, ...this.intermediateSettings };
    };

**Comment by shikhaBasra** [comment]
Can you please provide the plunker for the same?

**Comment by Thasli789** [comment]
@sourabhdeep its works for me...☺️ Thanks  a lot
