### ISSUE TITLE
data is not loading when you push to array

### ISSUE THREAD

**Issue by indraraj26** [akveo/ng2-smart-table#1062]
Hi, 

Data is not getting loaded in dom, when you use push method instead of direct assign. I have tried with load and refresh but it is not working.

To reproduce stackblitz: https://stackblitz.com/edit/example-ng2-smart-table-p8zvjq?file=src%2Fapp%2Fapp.component.ts 

Issue :
1. I am using bootstrap 4 in project and it is adding form-control class to ng2-smart-table too, how can i disable that i dont want to bootstrap input in ng2 smart table
2. /deep/ is not working in angular 8 also ::ng-deep too with scss, is there any way to fix this ng2-smart-table. 

Thank you.

**Comment by nvmnghia** [comment]
> Hi,
> 
> Data is not getting loaded in dom, when you use push method instead of direct assign. I have tried with load and refresh but it is not working.
> 
> To reproduce stackblitz: https://stackblitz.com/edit/example-ng2-smart-table-p8zvjq?file=src%2Fapp%2Fapp.component.ts
> 
> Issue :
> 
> 1. I am using bootstrap 4 in project and it is adding form-control class to ng2-smart-table too, how can i disable that i dont want to bootstrap input in ng2 smart table
> 2. /deep/ is not working in angular 8 also ::ng-deep too with scss, is there any way to fix this ng2-smart-table.
> 
> Thank you.

Could you share your solution?

**Comment by nvmnghia** [comment]
Okay I found the solution: use `LocalDataSource`, particularly its `load()` method. However, `add()` doesn't work in my case. Hope it's not a bug, and the error is on my part.

**Comment by metacrawler23** [comment]
> Okay I found the solution: use `LocalDataSource`, particularly its `load()` method. However, `add()` doesn't work in my case. Hope it's not a bug, and the error is on my part.

Can you share your code here?

**Comment by LoriCollier** [comment]
It worked in the example if you removed the timeout. 
`  constructor() {

    this.users.push(
    {
      id: 1,
      username: "Bret",
      email: "Sincere@april.biz",
      list: {
        name: 'leeee'
      }
    },
    {
      id: 2,
      name: "Ervin Howell",
      username: "Antonette",
      email: "Shanna@melissa.tv"
    },

    // ... list of items

    {
      id: 11,
      name: "Nicholas DuBuque",
      username: "Nicholas.Stanton",
      email: "Rey.Padberg@rosamond.biz"
    })
  
    this.source.load(this.users)
  }
}`

https://stackblitz.com/edit/example-ng2-smart-table-2whhmd
