### ISSUE TITLE
disable cursor: pointer on action button

### ISSUE THREAD

**Issue by indraraj26** [akveo/ng2-smart-table#1072]
Is there any way to disable cursor:pointer and add cursor: not-allowed based on condition in action column?

**Comment by SashaSkywalker** [comment]
Hi @indraraj26, you can add custom class on table:

```css```
::ng-deep ng2-smart-table.custom .ng2-smart-action-add-add {
  cursor: not-allowed;
}

```

**Comment by indraraj26** [comment]
Hi @SashaSkywalker , 

Thank you replying, 

i can see we have class there we can add this custom but this will be applied for whole column of action where as i need for one row of action.

Consider i have 4 rows, 2 are needs to be disable aka cursor: not-allowed on action button; 

It will be great to have custom css property for action button, Over all this package is awesome for inline and external mode <3

**Comment by SashaSkywalker** [comment]
hmm, maybe `rowClassFunction` option can be useful for you

**Comment by indraraj26** [comment]
Hi @SashaSkywalker, Yes thank you it works. I just had to check nested css something like this

>  tr .disable-custom ng2-smart-table.custom .ng2-smart-action-add-add.

Thank You 
#closing
