### ISSUE TITLE
a question about how to handle ServerDataSource?

### ISSUE THREAD

**Issue by wgl-19** [akveo/ng2-smart-table#1080]
I use   the ServerDataSource,but it seems to i can not handle the data from serve ,for example ,I want to add a index to table at every row. And i want to chang some field ,such as  transform number to characters，so i need to handle sourcedata.So how can i do this ?Plz

**Comment by wgl-19** [comment]
i have solved this problem.

**Comment by newguru-25** [comment]
you should post answer no ?
