### ISSUE TITLE
Add custom action button based on row value.

### ISSUE THREAD

**Issue by mPishtra** [akveo/ng2-smart-table#1084]
I know that on ng2-smart-table you can add custom action buttons. 
I also know on how to do something when one of these buttons is pressed.

My question is: How can I add a custom action button based on the value of a row? 
(For example: If value of column X is X1, then add a custom action button on this row)

Thank you

**Comment by Remusqs1** [comment]
Please! Anyone knows a solutions fo this?

**Comment by azurehari** [comment]
Please anyone share the solution for this.. is it possible?
