### ISSUE TITLE
ng2 Smart Table date column is not sorting

### ISSUE THREAD

**Issue by faizaldong** [akveo/ng2-smart-table#1085]
Hello folks,
In my Ng2 smart table grid have several columns. One of the column is Date. The rest of column can do sorting but only Date column can't do sorting. Below is config for my Date column.

**_on top_**
import { DatePipe } from '@angular/common';

**_column configuration_**

> 
        lastLoginTime: {
          title: 'Last Login',
          width: '15%',
          filter: false,
          valuePrepareFunction: (lastLoginTime: any) => {
            return new DatePipe('en-US').transform(lastLoginTime, 'M/d/yyyy')
          }
        }

and my table grid
<img width="627" alt="Screenshot 2019-10-01 at 10 03 41 AM" src="https://user-images.githubusercontent.com/17352624/65929045-eb60d400-e432-11e9-9bf5-cd6e1dd28dee.png">

from the image I already sort the Date column to **desc** but the date is not sorting at all
Anyone face same issue? how you guys fix this?

thank you

cc: @32penkin @KostyaDanovsky @KovalM @SashaSkywalker @Tibing @yggg

**Comment by crakdelpol** [comment]
I've used a custom compareFunction (see it on [documentation](https://akveo.github.io/ng2-smart-table/#/documentation))

```
export const sortDate = (direction: any, a: string, b: string): number => {
        let first = Number(new DatePipe('en-US').transform(a, 'yyyyMMdd'));
        let second = Number(new DatePipe('en-US').transform(b, 'yyyyMMdd'));

        if (first < second) {
            return -1 * direction;
        }
        if (first > second) {
            return direction;
        }
        return 0;
}
```
and on settings 
```
 lastLoginTime: {
      title: 'Last Login',
      width: '15%',
      filter: false,
      compareFunction: sortDate
      valuePrepareFunction: (lastLoginTime: any) => {
        return new DatePipe('en-US').transform(lastLoginTime, 'M/d/yyyy')
      }
    }
```
Try it

**Comment by lenichols** [comment]
@crakdelpol this worked for me - sorting works as expected with my dates now! Thanks for this snippet!

**Comment by rami-alloush** [comment]
I believe this should be closed

**Comment by faizaldong** [comment]
Ok let me close the issue, and thanks @crakdelpol for helping out !

**Comment by ankita20051997** [comment]
sorry but i have date format 'MM/DD/YYYY hh:mm:ss a' and i have to sort with this format ... i tried above solution, it is working fine but for example : - i have 5 entries with same date so it is only sorting based on date but i want sorting with date and time both for my column..
please give me any solution

**Comment by crakdelpol** [comment]
try with  let first = Number(new DatePipe('en-US').transform(a, 'yyyyMMddhhmm')); instead of  let first = Number(new DatePipe('en-US').transform(a, 'yyyyMMdd'));

**Comment by vijaya-likhar** [comment]
I am looking for sort function on column of table(Ng2SmartTable) in angular project.

column name: Date
condition: 
1.First  by date in descending order
2.Then by date in ascending order
3.Then should not sort by date ( which is default)


also using API to fetch data for all 3 condition.

Plz help me on that
