### ISSUE TITLE
The checkbox is too big. How do I make it smaller

### ISSUE THREAD

**Issue by HuangLuGuang** [akveo/ng2-smart-table#1090]
I only added in the setting, selectMode: 'multi',
How do I control the size of the checkbox?
please help me!
![20191012153619](https://user-images.githubusercontent.com/42086535/66697207-189c6480-ed06-11e9-9ba2-e46695b9f6f8.png)
my settings:
`settings = {
    selectMode: 'multi',
    add: {
      addButtonContent: '<i class="nb-plus"></i>',
      createButtonContent: '<i class="nb-checkmark"></i>',
      cancelButtonContent: '<i class="nb-close"></i>',
    },
    edit: {
      editButtonContent: '<i class="nb-edit"></i>',
      saveButtonContent: '<i class="nb-checkmark"></i>',
      cancelButtonContent: '<i class="nb-close"></i>',
    },
    delete: {
      deleteButtonContent: '<i class="nb-trash"></i>',
      confirmDelete: true,
    },
    columns: {
      id: {
        title: 'ID',
        type: 'number',
      },
      firstName: {
        title: 'First Name',
        type: 'string',
      },
      lastName: {
        title: 'Last Name',
        type: 'string',
      },
      username: {
        title: 'Username',
        type: 'string',
      },
      email: {
        title: 'E-mail',
        type: 'string',
      },
      age: {
        title: 'Age',
        type: 'number',
      },
    },
  };
`

**Comment by hope4555** [comment]
add this to your SCSS

:host /deep/ .ng2-smart-action-multiple-select{
  text-align: center;
}

:host /deep/ .ng2-smart-action-multiple-select > input{
  width:25px;
  height:25px;
  display: unset;
}

**Comment by DilanGeek** [comment]
Works for me tnks :!!

**Comment by SANDIPKEDIA** [comment]
Thanks bro @hope4555

**Comment by nikesh9220** [comment]
[This Solution ](https://github.com/akveo/ng2-smart-table/issues/1090#issuecomment-544202873) worked for me.
I have tried it in Styles.Scss but it is not worked then applied on Component.Scss file and it was worked. Thanks :)

**Comment by liloy292** [comment]
SassError: expected selector.

**Comment by NomanKader** [comment]
I have added the above code that have been mentioned above by @hope4555  into the theme.scss file and it work well . 🎉

**Comment by devin1996** [comment]
Worked for me, thanks ! 👍🏼
