### ISSUE TITLE
I want to format my data

### ISSUE THREAD

**Issue by xianrui** [akveo/ng2-smart-table#11]
the data like this  {"name":"name","state":1}  

I want to show data like this {"name":"name",state:"true"}

I use filterFunction attr but not show true

Excuse me what should I do?

**Comment by nnixaa** [comment]
Hey @xianrui, this is not documented (looks like missed from the documentation!) but there is a `valuePrepareFunction` property on the column, so that you could specify a formatter for a value before it will be inserted in a cell like this:
```
{
your_column: {
  title: 'some',
  valuePrepareFunction: (value) => { return value === 1 ? 'true' : 'false' }
}
}
```

**Comment by xianrui** [comment]
It's Very Good !
This is what I want!
Thank you very much!

**Comment by nnixaa** [comment]
@xianrui glad it helped!

**Comment by anshulbahukhandi** [comment]
Hey
1. Is there a way I can process the  filter value before sending it to server data source ? I want to trim the column filter value i.e remove it's leading and trailing white space before it's sent to the server data source . I tried filterFunction but it's still making XHR request for blank string
2. Also can we specify the minimum letter at which the KHR request should start. Right now it makes the request to the server even for one letter. How can I change this behavior to only make request for atleast 3 letters?

Thanks

**Comment by danaERadwin** [comment]
How can I deal with presenting multiple keys from the same object? 
the source:
{
 "id": "1",
"customer": {"name":"name","state":1}
}
I would want to do the following:
```
{
  id: {
    title: 'ID'
  },
  customer: {
    title: 'ID',
    valuePrepareFunction: (value) => { return customer.id }
  },
  customer: {
    title: 'ID',
    valuePrepareFunction: (value) => { return customer.state }
  }
}
```

BUT of course, I cannot do that since I am using duplicate column id\column name.
What is the solution?

**Comment by paulsynth** [comment]
Hi, guys. I've found the solution to @danaERadwin problem, and also mine!!

The trick is on the valuePrepareFunction() that receives TWO params, cell (value) and row (the complete object), so the solution is:

{
  id: {
    title: 'ID'
  },
  'customer.name': {
    title: 'Name',
    valuePrepareFunction: (cell, row) => { return row.customer.name }
  },
  'customer.state': {
    title: 'State',
    valuePrepareFunction: (cell, row) => { return row.customer.state }
  }
}

I hope it's also fine for you!

**Comment by aktasmuhammet** [comment]
Did you can find the solution for filterFunction? @jim060

**Comment by charbonnier666** [comment]
> compareFunction

still want the solution too...
