### ISSUE TITLE
Cursor icon in table view

### ISSUE THREAD

**Issue by codafish-gmbh** [akveo/ng2-smart-table#1107]
When you move the mouse over a table, the mouse icon changes depending on the content underneath. If it is text, the text mouse icon is displayed. Otherwise, the typical arrow icon is shown. Could the arrow icon always be displayed regardless of the content?

![text_cursor](https://user-images.githubusercontent.com/2080312/68749503-9fdb4180-05fe-11ea-82f3-25c6303886b5.jpg)
![arrow_cursor](https://user-images.githubusercontent.com/2080312/68749505-9fdb4180-05fe-11ea-9633-341c78dbc5fe.jpg)

**Comment by timoberlin** [comment]
One more note: maybe the whole row can be configured as a link, when the event "userRowSelect" is configured? Then the user would notice that the row can be clicked. In that case a hand mouse icon would be shown.
