### ISSUE TITLE
ng build --prod breaks due to  /deep/ instead of ::ng-deep in angular 8

### ISSUE THREAD

**Issue by Nyongo** [akveo/ng2-smart-table#1113]
\node_modules\ng2-smart-table\ng2-smart-table.component.scss

Fix
Replace   /deep/  with ::ng-deep

**Comment by SnakyBeaky** [comment]
This was fixed in 1.5.0 PR https://github.com/akveo/ng2-smart-table/pull/1017 https://github.com/akveo/ng2-smart-table/commit/1bee9c412ac1d8558a5f9b866bbb78311c0ee8a2
