### ISSUE TITLE
Expected CSS styles not working

### ISSUE THREAD

**Issue by siddharthaReddy** [akveo/ng2-smart-table#112]
Our current application has the requirement to be responsive, so we are using bootstrap 3. App is still in initial stages and all the styles are applied only using bootstrap classes. 

Smart-table that has been included using npm install doesn't have the actual/expected styles from demos.

![smart-table-styles](https://cloud.githubusercontent.com/assets/10968800/21333609/f9e12df2-c61e-11e6-958b-c98a53aca7d0.PNG)

The labels and text outside of table are of font-size 14 px, where as text inside tables is getting computed to 8.75px. Also, table's border-top doesn't appear.

I have tried adding classes to table and then have those classes define styles in module and component based css files but still doesn't apply. 

Is there a way to customize the styles for smart-tables ?

Thanks in advance.

**Comment by DickRiversDuGettho** [comment]
i have the same issue, i don't understand how to apply styles, please, Any explanations.

**Comment by JavaCoder12** [comment]
I am also having the same problem while using this smart table with Bootstrap 3 can some please throw light for us to customize the css  in order to increase the font of table content

**Comment by neo4u** [comment]
Any update on this? Were you able to make any CSS customizations?

**Comment by stefanofalasca** [comment]
Me too same problem

**Comment by neo4u** [comment]
@stefanofalasca : This was a false alarm for me. I hadn't imported the file to modify the theme correctly.

**Comment by vamsyvirureddy** [comment]
mee too same problem

**Comment by youneschaoui** [comment]
problem source : default ng2-smart-table style is erasing any post defined css rules. I am forking the repo to comment css file

**Comment by JavaCoder12** [comment]
@youneschaoui  - Please let us know once you commit the code to repo. Thank you for finding the root cause and willing to fork the fix to the repo.

**Comment by Akshaymisal5** [comment]
me too same problem

**Comment by the-pinky-man** [comment]
The issue is most likely that the tr/th style specifies 0.875rem for the font size and Bootstrap 3 by default has a small base font, maybe 10px?

0.875rem means that the font sizes for the table rows and headers with be 0.875x the size of the base/root font - which is small in Bootstrap.

So you can either customise/modify your Bootstrap configuration to a bigger base font size or update the styles for the table rows/headers to be something bigger than 0.875rem.

However, it would be good to override the tr/th values as part of the components configuration.

**Comment by a4amitava** [comment]
Me too have the same issue . any update or work around please ?

**Comment by abhishek3999** [comment]
I have also same issue.I am not able to apply extra css to smart table.
I am using @angular/material/prebuilt-themes/indigo-pink.css.
so table is not showing with neat border and aligned.
please answer asap.

**Comment by srinikoganti** [comment]
Having same problem. Can't apply bootstrap classes for the table. Any solution ?

**Comment by DickRiversDuGettho** [comment]
No i make my own table

Le 11 juil. 2017 4:33 PM, "Srini Koganti" <notifications@github.com> a
écrit :

**Comment by abhishek3999** [comment]
the table is designed by using bootstrap.If you have to use or apply css externally for the table then 
eg> td{backgroundColor:pink}
th{  font:bold;
} use like this way
Thanks

**Comment by davidmartinezros** [comment]
Hi!

I migrate the version of angular from 2 to 4 for use the new version of the component.

In my case, the ng2-smart-table component, version ^1.2.2, doesn't show the cell style border.

I have to define any style for showing? Or the styles of the tables changes from the version 0.6.0?

Thanks in advanced,

David

**Comment by abhishek3999** [comment]
Hi,

You have define style by externally in styles.css.

Thanks

**Comment by Anky001** [comment]
use below configuration in the setting object

**attr: {
        class: 'table table-bordered'
      },**

and 

 **:host /deep/ ng2-smart-table { 
    font-size: 16px; 
}**

eg . 
settings = {
  columns: {
    id: {
      title: 'ID'
    },
    name: {
      title: 'Full Name'
    },
    username: {
      title: 'User Name'
    },
    email: {
      title: 'Email'
    }
  },
attr: {
        class: 'table table-bordered'
      }
};

**Comment by DarioN1** [comment]
I have the same problem, do you have any updates ?
