### ISSUE TITLE
Checkbox is reset after filter

### ISSUE THREAD

**Issue by obarazan** [akveo/ng2-smart-table#1127]
Hi,

I'm using in ng2 smart table and I want to add a checkbox column to select rows, I added a "selectMode: 'multi'" and the selected rows are reset after I filter column.
The issue reproducing in my custom filter and the default filter.
any suggestion?

![Capture](https://user-images.githubusercontent.com/47638725/72877808-5eec6100-3d02-11ea-9a34-80c00367f15e.JPG)

**Comment by obarazan** [comment]
working with the following solution:

`selectRowsFunction() {
    this.subscriptions.push(
      this.source.onChanged().subscribe((change) => {
        switch (change.action) {
          case 'sort':
          this.systemDefinitionTable.grid.getRows().forEach(row => {
            if (this.selectedRows.find(elem => elem.Name === row.getData().Name)) {
               this.systemDefinitionTable.grid.multipleSelectRow(row);
            }
          });
            break;
          case 'filter':
          this.systemDefinitionTable.grid.getRows().forEach(row => {
            if (this.selectedRows.find(elem => elem.Name === row.getData().Name)) {
               this.systemDefinitionTable.grid.multipleSelectRow(row);
            }
          });
          break;
          case 'paging':
          this.systemDefinitionTable.grid.getRows().forEach(row => {
            if (this.selectedRows.find(elem => elem.Name === row.getData().Name)) {
               this.systemDefinitionTable.grid.multipleSelectRow(row);
            }
          });
        }
      }),
    );
  }`

**Comment by ranjeetMishra1990** [comment]
Can you please elaborate it
