### ISSUE TITLE
[1.6.0] Error on Compiling

### ISSUE THREAD

**Issue by macchie** [akveo/ng2-smart-table#1144]
Hello there, i recently updated to Angular9 + Nebular 5.0.0 and ng2-smart-table version 1.6.0 but i'm not able to correctly build my project, here is the error im getting:

```
ERROR in ./node_modules/ng2-smart-table/ng2-smart-table.ngfactory.js
Module not found: Error: Can't resolve '../@akveo/ng2-completer/ng2-completer.ngfactory' in '~/dev/project/node_modules/ng2-smart-table'
```

any idea on how to solve this?

Thanks!

**Comment by macchie** [comment]
OK Fixed it!

I wasn't importing this in my app module:

```
import { Ng2CompleterModule } from '@akveo/ng2-completer';
```

if anyone gets the same error this will fix it!

**Comment by zzkkss** [comment]
> OK Fixed it!
> 
> I wasn't importing this in my app module:
> 
> ```
> import { Ng2CompleterModule } from '@akveo/ng2-completer';
> ```
> 
> if anyone gets the same error this will fix it!

it'sWorked
