### ISSUE TITLE
CRUD Operation on smart table

### ISSUE THREAD

**Issue by sureshhustle** [akveo/ng2-smart-table#117]
Hi,
    Guys i am able to load all data from database , but i can't able to make CRUD operations on this table, Help me some ideas to make these operations

**Comment by radha89** [comment]
You have to use eventbinding for createConfirm, deleteConfirm and editConfirm. Check out this stakoverflow post:

[http://stackoverflow.com/questions/40404378/edit-and-create-with-ng2-smart-table](url)

**Comment by sureshhustle** [comment]
ya thank you i tried with resolve reject , which work on local file when i refresh it will restored again, will you please give me the sample code for any of one operation which done on server database.

**Comment by webdeveloperninja** [comment]
@radha89 hey you SO link doesnt seem to be working do you know if it moved? Same issues here

**Comment by radha89** [comment]
Oops sorry about that. check this [link](http://stackoverflow.com/questions/40404378/edit-and-create-with-ng2-smart-table)

**Comment by meriem-hm** [comment]
hi @sureshhustle  , i tried to load data from my database "mongo database" to the ng2-smart table  but it dosen't work, would you please help me ,
