### ISSUE TITLE
ERROR in Node does not exist: C:/projects/ma/CustomerPortal-master/node_modules/ngx-smart-table

### ISSUE THREAD

**Issue by Tavethiya** [akveo/ng2-smart-table#1183]
![image](https://user-images.githubusercontent.com/48272963/85919666-0447ca00-b88b-11ea-9d08-7a50c32cf018.png)

getting above error on ng serve

**Comment by AhmadKNaji** [comment]
Try this in your folder terminal: npm install --save ng2-smart-table
then import it to you app.module like this: import { Ng2SmartTableModule } from 'ng2-smart-table';
afterwards implement it in your imports: 
@NgModule({
  imports: [
    // ...
    
    Ng2SmartTableModule,
    
    // ...
  ],
