### ISSUE TITLE
Make row selection more customisable

### ISSUE THREAD

**Issue by fvlad** [akveo/ng2-smart-table#13]
Hey. How about adding support to disable automatic row selection?

Currently, there is a callback `(rowSelect)`, but it doesn't seem to be very useful for me, since it automatically triggers on the first table row when the data is initially loaded and it seems to select other rows upon different actions (like navigation, row deletion and etc.). So it means I cannot predict user selecting a specific row, it happens on its own.

What I'm trying to achieve is an ability to trigger some action only when _user_ selects a row. For example, table can contain a list of items, and when user clicks on a particular row it should open a separate page with item information. It could also be achieved by adding a custom action, but it seems to be impossible at the moment too.

After investigation, I believe an additional configuration property would work. For example, it could cause `determineRowToSelect` in _Grid_ return null. I can do a PR if it's fine for you.

**Comment by LoscaraDK** [comment]
i quit, this cant be used

**Comment by nnixaa** [comment]
Hi @fvlad, going to release a (userRowSelect) event which will be fired only on when a user clicks on a row

**Comment by nnixaa** [comment]
or do you also need to disable the automatic row selection at all?

**Comment by fvlad** [comment]
Hi @nnixaa. Thank you. I think this kind of event is what I need, as long as it doesn't trigger automatically on page load, navigation and etc.

**Comment by nnixaa** [comment]
okay @fvlad, checkout 0.2.2 version for rc5 and 0.1.8 for rc4.

**Comment by fvlad** [comment]
Thank you, it works.
But now there is another problem. Not sure if it is the right place to discuss it, but still.
After updating to 0.1.8 it ignores my _actions_ configurations. I have it defined like the following:
`actions: {
      add: false,
      edit: false,
      delete: false
    }`
But the Actions column is till displayed.

**Comment by nnixaa** [comment]
right, there is some regression our of the fix I made, will have a look shortly, here's another issue for this https://github.com/akveo/ng2-smart-table/issues/19.
