### ISSUE TITLE
Table not work when I refresh page 

### ISSUE THREAD

**Issue by shaimaaezo** [akveo/ng2-smart-table#1337]
Hi,
this issue appears when I come to refresh page component,
this is my code => 
      this.settings = {
        mode: 'internal',
        actions: {
          title: data['Action'],
          add: false,
          delete: false,
        },
        edit: {
          editButtonContent: '<i class="nb-edit"></i>',
        },
        columns: {
          code: {
            title: data['creditLimitCode'],
            type: 'string',
          },
          name: {
            title: data['creditLimitName'],
            type: 'string',
          },
          days: {
            title: data['creditLimitDays'],
            type: 'string',
          },
          discount: {
            title: data['creditLimitDiscount'],
            type: 'string',
          },
        }
      }

________________________
<ng2-smart-table class="creditlimit-smart-table" [settings]="settings" [source]="source" (edit)="onEdit($event)">
    </ng2-smart-table>
___________________________
  ::ng-deep .creditlimit-smart-table {
    .form-control {
      color: nb-theme(form-control-color);
    }
  }

<img width="625" alt="h" src="https://user-images.githubusercontent.com/30451219/205637211-1c196278-973c-4044-8b00-b32bfa4b5c96.PNG">

**Comment by javapach** [comment]
this was happening to me too, but you need to declare and set your settings as a global variable:

```
@Component({
  selector: "yourComponent",
  templateUrl: "./yourComponent.component.html",
  styleUrls: ["./yourComponent.component.scss"],
})

export class yourNameComponent{

globalVariable1: any;
globalVariable2: any;
globalVariableN: any;

// declare your seettings here as global
 settings = {
    columns: {...},
    mode: 'internal',
   actions:{...}
  ....
  };

  constructor(){ ... }
}
```

**Comment by shaimaaezo** [comment]
> this was happening to me too, but you need to declare and set your settings as a global variable:
> 
> ```
> @Component({
>   selector: "yourComponent",
>   templateUrl: "./yourComponent.component.html",
>   styleUrls: ["./yourComponent.component.scss"],
> })
> 
> export class yourNameComponent{
> 
> globalVariable1: any;
> globalVariable2: any;
> globalVariableN: any;
> 
> // declare your seettings here as global
>  settings = {
>     columns: {...},
>     mode: 'internal',
>    actions:{...}
>   ....
>   };
> 
>   constructor(){ ... }
> }
> ```

thank you very much, its work
