### ISSUE TITLE
Column width

### ISSUE THREAD

**Issue by FaisalAriyanto** [akveo/ng2-smart-table#134]
Is there a way to quickly setup the width for each colom?

**Comment by PrazSam** [comment]
I'm facing the same issue. @FaisalAriyanto you are asking about a "quick" way. It seems you have a workaround or..?

**Comment by FaisalAriyanto** [comment]
@PrazSam My bad way to set width:

ngAfterViewInit() {
        document.getElementsByClassName('column_name')['0'].style.width = '100px'
 }

**Comment by PrazSam** [comment]
Since there are no any other way yet, this is the greatest way. @FaisalAriyanto Thanks for saving my day.

**Comment by alifatic** [comment]
@FaisalAriyanto i want to ask, do u know how to add overflow-x , inside tbody, i've added in css but not working

**Comment by PrazSam** [comment]
@alifatic Why overflow-x just for tbody ? I don't know what you really looking for. If you are trying to make the table horizontally scrollable, just use table inside a div and make it scrolable.
`<div class="smart-table-container">
    <ng2-smart-table ..... > </ng2-smart-table >
</div>
.smart-table-container{
    overflow-x: scroll;
}
//you may use min width for the table.
.ng2-smart-table  {
    min-width: 1500px;
}`

**Comment by ManpreetSingh80** [comment]
You can also use css class in column or just add data in html format and define width there.

**Comment by sushanzh** [comment]
@FaisalAriyanto I was trying your workaround below where Region is my column name. I placed the function in the component.ts file. It didn't seem to take any effect. Did I miss anything? I'm looking for a way to set the width of each column, or alternatively configure it so that the column width accommodates the text value inside the cells full but don't wrap to the next row (go horizontally across, not wrap to the next row. Thank you for your help!

ngAfterViewInit() {
document.getElementsByClassName('Region')['0'].style.width = '100px'
}

**Comment by sushanzh** [comment]
@ManpreetSingh80  I tried adding class: 'wide' to the column setting, it doesn't take effect either. I think I'm missing something...

settings = {
        columns: {
            region: {
                title: 'Region',
                filter: false,
                class: 'wide'
            },
...
}

**Comment by ManpreetSingh80** [comment]
@sushanzh You can try html type

`title: 'Region',
 type: 'html',
 filter: false,
 valuePrepareFunction: (value) => {
         return  '<div class="wide">' + value + '</div>';
  }`

**Comment by FaisalAriyanto** [comment]
@sushanzh Maybe ngAfterViewInit cannot find your table, i run script there because i expect that table show in DOM and can find column name and change width manual by javascript.

**Comment by sushanzh** [comment]
@FaisalAriyanto and @ManpreetSingh80  thank you for your replies. I have tried again, and the html type method works for me! Thank you!!!

**Comment by gregoiremotot** [comment]
I had to downgrade to 1.4.0 and `width` property works 
`npm install --save ng2-smart-table@1.4.0`

**Comment by Ajinkyadon** [comment]
> @alifatic Why overflow-x just for tbody ? I don't know what you really looking for. If you are trying to make the table horizontally scrollable, just use table inside a div and make it scrolable.
> 
> ```
> <div class="smart-table-container">
>     <ng2-smart-table ..... > </ng2-smart-table >
> </div>
> ```
> 
> ```
> .smart-table-container{
>     overflow-x: scroll;
> }
> ```
> 
> you may use min width for the table.
> 
> ```
> .ng2-smart-table  {
>     min-width: 1500px;
> }
> ```

Thanks, man you help me a lot.
