### ISSUE TITLE
Want to delete actions column. i mean the entire crude operation column.how to do it.

### ISSUE THREAD

**Issue by new2angular2** [akveo/ng2-smart-table#137]

**Comment by nekser** [comment]
This hepled me:
```
settings = {
        actions: false,
        ....
}
```

**Comment by anacesponda** [comment]
@lexzhukov Is there any way to remove create and update actions keeping the delete action? Thanks!

**Comment by alexsc123** [comment]
actions: {
            add: false,
             edit:false
        }

**Comment by git-Bryan** [comment]
Thanks. But after adding this
actions: {
add: false,
edit:false
}
the Add New button was still visible. How do I hide it?

**Comment by alexsc123** [comment]
Hi,
I just tested this and when the settings is `add:false` then the smart table doesn't show the button - please test it again.
If it doesn't work - a bypass for you might be:
```
 add: {
            addButtonContent: ''
         }
```
Now the button will not be visible.
Alex.

**Comment by git-Bryan** [comment]
![snip1](https://user-images.githubusercontent.com/17102619/29563348-078dafca-8735-11e7-9e5e-c6fdb49f1888.PNG)

I tried that too but its still visible

**Comment by git-Bryan** [comment]
please, is there any other way Alex?

**Comment by git-Bryan** [comment]
Thanks a lot Alex. I figured it out.

I had to do the setting in the Ng2SmartTableComponent.


________________________________

**Comment by jesusce21** [comment]
@git-Bryan 

I don't know why, but when you change the column position, it's work. Write right instead left.

actions: {
            columnTitle: '',
            position: 'right'
          },
add: {
            addButtonContent: "",
}

**Comment by ashishpawar2489** [comment]
settings = {
        actions: false,
        ....
}

IMP: actions:false has to be the first line in the settings object. If its not placed at the first object, It will not work

**Comment by hjain-spcg** [comment]
You will need to call this

this.table.initGrid();  

You will need to call this, as somehow binding does not take into effect for some of the features when you change settings object.  I think because rendering is done some values via a method call, therefore set once unless you call initGrid.  

Not clear why table has settings property and table.grid has settings property

**Comment by JaiKumaresh** [comment]
Please, take a look & try it. It's work for me.(https://stackoverflow.com/questions/50817642/angular-5-ng2-smart-table-hide-disable-actions-column-conditionally/52781288#52781288)

**Comment by miguelleitevieira** [comment]
It's possible to change the table settings after the html be loaded?
I'm trying to disable conditionally after user add some data into the table, but the changes are not detected.

**Comment by rodriguesnavil** [comment]
<img width="1000" alt="Screenshot 2021-03-19 at 12 38 07 AM" src="https://user-images.githubusercontent.com/32533176/111683379-64343580-884b-11eb-9498-aed4848972d5.png">
If you want to disable the whole row above, you can use the below configuration
 
```
settings = {
    hideSubHeader: true,
    actions: {
      add: false,
      edit:false,
      delete: false
    },
...
}
```
