### ISSUE TITLE
Customize action column

### ISSUE THREAD

**Issue by Frisky-** [akveo/ng2-smart-table#142]
Is it possible to change the action column position to the right ?

**Comment by Frisky-** [comment]
nvm found it, if someone else is looking for that aswell just add actions: { position: 'right' } in the settings.

**Comment by madhuinwiter** [comment]
I am facing another problem which is related to this.

I did as Frisky said, but when I click on edit or add new row the action buttons are displaying left side. Please see the below images. I need those buttons also on right side only.

Please some one help me to fix this issue.

![exempportal 1](https://cloud.githubusercontent.com/assets/7322186/24090175/dea5046e-0d63-11e7-8424-4957f2144a8c.png)
![exempportal](https://cloud.githubusercontent.com/assets/7322186/24090176/dfc6a06e-0d63-11e7-9fa4-6303025ca071.png)

**Comment by Akshaymisal5** [comment]
I am facing the same problem. When I am using position 'right' and click on edit mode, position of action column becomes 'right'.

**Comment by Frisky-** [comment]
After i fixed the position i saw that it doesn't work correct so i gave up on the lib, sorry if i mislead someone. :(

**Comment by Akshaymisal5** [comment]
No worry,  I have fixed that issue in the repository and created a pull request. might be integrated. :)

**Comment by hemnath11** [comment]
I'm also using this actions: { position: 'right' } in settings but the actions column is displaying in left side only

**Comment by madhuinwiter** [comment]
@Akshaymisal5 Is your PR approved? If I update the code can get your changes?

**Comment by madhuinwiter** [comment]
This bug was fixed with the latest version 1.0.0. Thank you @Akshaymisal5

**Comment by arundhati88** [comment]
Its working for me well. Thank u
