### ISSUE TITLE
npm-shrinkwrap.json install all devDependencies

### ISSUE THREAD

**Issue by Chocobozzz** [akveo/ng2-smart-table#143]
It seems that when `npm-shrinkwrap.json` was added to the project, when we install ng2-smart-table as a dependency we install all the devDependencies too.

Version 0.5.1-0 does not seem to be affected.

    % npm install ng2-smart-table@0.5.1-0
    % ll node_modules/ng2-smart-table/ | grep node_modules | wc -l
    0

    % npm install ng2-smart-table@0.5.1-1
    % ll node_modules/ng2-smart-table/node_modules | wc -l
    742

**Comment by LexZhukov** [comment]
Hey @Chocobozzz, could you update ng2-smart-table to the latest version? This bug was fixed in 0.5.2-1.

**Comment by Chocobozzz** [comment]
Thanks @LexZhukov I confirm it's fixed :)
