### ISSUE TITLE
Get compiling error

### ISSUE THREAD

**Issue by zh-wowtv** [akveo/ng2-smart-table#148]
> ERROR in /Users/Public/Projects/myproject/node_modules/ng2-smart-table/src/ng2-smart-table/lib/data-source/server/server.data-source.ts (70,12): Type 'Observable<Response>' is not assignable to type 'Observable<any>'.
  Property 'source' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.)

Is it possible because I generated the project in angular-cli 1.0.0-beta.28.3?

Any idea? Thanks.

By the way, it's very easy to reproduce the problem.

> ng new myproject
> cd myproject
> npm i ng2-smart-table --save

And then add the follow line to `app.module.ts`:

```
import { Ng2SmartTableModule } from 'ng2-smart-table';

@NgModule({
  declarations: [
    AppComponent,
    XlsComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    Ng2SmartTableModule,
    HttpModule
  ],

```

**Comment by zh-wowtv** [comment]
Fixed the issue.

ng2-smart-table's package.json contains this:

```
  "dependencies": {
    "ng2-completer": "^1.0.0",
    "rxjs": "~5.0.2"
  },
```
but rxjs should be here instead:

```
  "peerDependencies": {
    "@angular/common": "2.4.4",
    "@angular/compiler": "2.4.4",
    "@angular/core": "2.4.4",
    "@angular/forms": "2.4.4",
    "rxjs": "^5.0.2"
  },
```

Should change to the source code?

**Comment by LexZhukov** [comment]
Hi, @zh-wowtv. Thanks for your issue investigation. Could you create pull-request with this fix?

**Comment by zh-wowtv** [comment]
@LexZhukov Done. But somehow through my another github account. Sorry for that.
