### ISSUE TITLE
CSS Customization while using ng2-smart-table with ng2-admin

### ISSUE THREAD

**Issue by neo4u** [akveo/ng2-smart-table#155]
Is there a way to override the CSS of the ng2-smart-table when used within ng2-admin?

The CSS used below don't seem to work.

https://github.com/akveo/ng2-admin/blob/master/src/app/pages/tables/components/smartTables/smartTables.scss

**Comment by neo4u** [comment]
This was my mistake. Making CSS changes on the above link works just fine. I made silly mistake.

**Comment by abhikhatri67** [comment]
@neo4u  what is the mistake ? 
can you update this ?

**Comment by neo4u** [comment]
It was too idiotic a mistake to mention it here. I was make the changes in the wrong file. :(

**Comment by NicholasLennox** [comment]
Your use of styling is exactly what I needed to have as a base to customize this thing. Thanks a lot :)
