### ISSUE TITLE
Export data to CSV or PDF

### ISSUE THREAD

**Issue by pranee1h** [akveo/ng2-smart-table#157]
How to export the table data and selected data to CSV or pdf file.

**Comment by SlickNutter** [comment]
use the "LocalDataSource" as the source for your table, then just use LocalDataSource's getAll method. From there you have to parse the data and rewrite it as in a CSV-format. If you want to get the selected row save the selected row in a private variable when you "hear" (userRowSelect), then write a method that takes care of passing that data to the parser & writter.
