### ISSUE TITLE
how to hide actions column ?

### ISSUE THREAD

**Issue by youneschaoui** [akveo/ng2-smart-table#176]
I use ng2-smart-table for display purpose. Actions column is auto-generated even if it's not mentioned in column list. How to hide it ?

**Comment by LexZhukov** [comment]
Please, take a look https://github.com/akveo/ng2-smart-table/issues/137.

**Comment by JaiKumaresh** [comment]
Please, take a look & try it. It's work for me.(https://stackoverflow.com/questions/50817642/angular-5-ng2-smart-table-hide-disable-actions-column-conditionally/52781288#52781288)
