### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by isuruhera** [akveo/ng2-smart-table#179]
D:\Projects\quickstart>npm run build

> angular-quickstart@1.0.0 build D:\Projects\quickstart
> tsc -p src/

node_modules/ng2-smart-table/src/ng2-smart-table/components/cell/cell-edit-mode/custom-edit.component.ts(37,57): error TS7006: Parameter 'event' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/components/cell/cell-edit-mode/custom-edit.component.ts(38,56): error TS7006: Parameter 'event' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/components/cell/cell-edit-mode/edit-cell-default.ts(12,12): error TS7006: Parameter 'event' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/components/cell/cell-edit-mode/edit-cell-default.ts(22,11): error TS7006: Parameter 'event' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/components/cell/cell-edit-mode/edit-cell.component.ts(29,12): error TS7006: Parameter 'event' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/components/cell/cell-editors/completer-editor.component.ts(34,21): error TS7006: Parameter 'event' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/components/cell/cell-view-mode/view-cell.component.ts(20,15): error TS7006: Parameter 'changes' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/components/cell/cell.component.ts(24,12): error TS7006: Parameter 'event' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/components/filter/filter.component.ts(42,11): error TS7006: Parameter 'event' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/components/pager/pager.component.ts(69,21): error TS7006: Parameter 'changes' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/components/title/title.component.ts(39,25): error TS7006: Parameter 'fieldConf' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/lib/data-set/cell.ts(8,31): error TS7006: Parameter 'value' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/lib/data-set/cell.ts(10,57): error TS7006: Parameter 'column' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/lib/data-set/data-set.ts(34,17): error TS7006: Parameter 'data' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/lib/data-set/data-set.ts(122,17): error TS7006: Parameter 'settings' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/lib/data-set/row.ts(34,11): error TS7006: Parameter 'data' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/lib/data-source/local/local.data-source.ts(13,5): error TS7018: Object literal's property 'filters' implicitly has an 'any[]' type.
node_modules/ng2-smart-table/src/ng2-smart-table/lib/data-source/local/local.data-source.ts(163,13): error TS7006: Parameter 'fieldConf' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/lib/data-source/local/local.data-source.ts(236,13): error TS7005: Variable 'mergedData' implicitly has an 'any[]' type.
node_modules/ng2-smart-table/src/ng2-smart-table/lib/data-source/local/local.sorter.ts(3,31): error TS7006: Parameter 'direction' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/lib/data-source/local/local.sorter.ts(3,42): error TS7006: Parameter 'a' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/lib/data-source/local/local.sorter.ts(3,45): error TS7006: Parameter 'b' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/lib/data-source/server/server.data-source.ts(43,37): error TS7006: Parameter 'res' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/lib/data-source/server/server.data-source.ts(60,38): error TS7006: Parameter 'res' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/lib/grid.ts(19,35): error TS7006: Parameter 'settings' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/lib/grid.ts(164,21): error TS7006: Parameter 'changes' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/lib/grid.ts(177,23): error TS7006: Parameter 'changes' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/lib/grid.ts(188,24): error TS7006: Parameter 'changes' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/lib/grid.ts(218,17): error TS7006: Parameter 'source' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/lib/grid.ts(249,17): error TS7006: Parameter 'status' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/lib/helpers.ts(1,26): error TS7006: Parameter 'val' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/lib/helpers.ts(9,29): error TS7006: Parameter 'val' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/lib/helpers.ts(26,25): error TS7006: Parameter 'arr' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/lib/helpers.ts(27,7): error TS7005: Variable 'clone' implicitly has an 'any[]' type.
node_modules/ng2-smart-table/src/ng2-smart-table/lib/helpers.ts(28,25): error TS7006: Parameter 'item' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/lib/helpers.ts(28,31): error TS7006: Parameter 'index' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/lib/helpers.ts(53,37): error TS7019: Rest parameter 'objects' implicitly has an 'any[]' type.
node_modules/ng2-smart-table/src/ng2-smart-table/lib/helpers.ts(67,7): error TS7005: Variable 'val' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/lib/helpers.ts(67,12): error TS7005: Variable 'src' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/lib/helpers.ts(67,17): error TS7005: Variable 'clone' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/lib/helpers.ts(69,26): error TS7006: Parameter 'obj' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/ng2-smart-table.component.ts(95,9): error TS7006: Parameter 'event' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/ng2-smart-table.component.ts(123,21): error TS7006: Parameter 'row' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/ng2-smart-table.component.ts(154,20): error TS7006: Parameter 'event' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/ng2-smart-table.component.ts(174,22): error TS7006: Parameter 'event' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/ng2-smart-table.component.ts(188,22): error TS7006: Parameter 'event' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/ng2-smart-table.component.ts(195,20): error TS7006: Parameter 'event' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/ng2-smart-table.component.ts(202,16): error TS7006: Parameter 'row' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/ng2-smart-table.component.ts(202,21): error TS7006: Parameter 'event' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/ng2-smart-table.component.ts(229,14): error TS7006: Parameter '$event' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/ng2-smart-table.component.ts(233,8): error TS7006: Parameter '$event' implicitly has an 'any' type.
node_modules/ng2-smart-table/src/ng2-smart-table/ng2-smart-table.component.ts(237,10): error TS7006: Parameter '$event' implicitly has an 'any' type.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ih\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.9.4
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular-quickstart@1.0.0 build: `tsc -p src/`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 build script 'tsc -p src/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc -p src/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ih\AppData\Roaming\npm-cache\_logs\2017-02-16T01_20_27_386Z-debug.log

D:\Projects\quickstart>

Please help..

**Comment by LexZhukov** [comment]
Hi, @isuruhera. Could you show your tsconfig.json?

**Comment by isuruhera** [comment]
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "es2015",
      "dom"
    ],
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true
  }
}

**Comment by LexZhukov** [comment]
@isuruhera, try to remove `"noImplicitAny": true, "suppressImplicitAnyIndexErrors": true`

**Comment by isuruhera** [comment]
Awesome . Thanks 👍

**Comment by MJAHEDSABRINE** [comment]
Hi,Could you help me please !!!
![image](https://cloud.githubusercontent.com/assets/25842518/24187841/2023a1ee-0edf-11e7-98cb-2649e6ab0e48.png)
