### ISSUE TITLE
Settings property update

### ISSUE THREAD

**Issue by geneeblack** [akveo/ng2-smart-table#19]
I noticed when attempting to set 
{
actions: {
edit:false,
delete: false,
update: false
}

in my page settings that it wasn't carrying forward into the table settings.

after looking at the settings property update code its looks like

deepExtend(this.settings, this.defaultSettings);

works when it is changed to 

deepExtend(this.defaultSettings, this.settings);

otherwise the page level settings get overwritten by the defaults;

https://github.com/akveo/ng2-smart-table/blob/master/src/ng2-smart-table/ng2-smart-table.component.ts#L181

**Comment by nnixaa** [comment]
@geneeblack yeah, this is a regression issue from this commit https://github.com/akveo/ng2-smart-table/commit/2ebac0ff9c36035ce17c02a851a5a46277f00f09, will have a look soon.

**Comment by nnixaa** [comment]
guys, could you try latest changes from master and let me know if everything works as expected? Thanks.

**Comment by geneeblack** [comment]
The way I was using settings was to send a partial description of new settings, i.e. 

settings = {
actions: {
edit:false,
delete: false,
update: false
columns: {...}
}


I can see in #20 that they may have been attempting to set the settings.columns directly on the settings property rather than the assigning the whole settings property. I can see where this wouldn't work because it is not triggering the settings change. Maybe some type of general accessor 'set(propertykey) that would then trigger the property change might be middle ground where individual properties in settings could be changed while still triggering the change. Otherwise you could strong type the settings object and have onchange for each element. Although I am happy to send the whole settings object with only those differences that I wish to change from the default as long as those settings are overlaid on top of the defaults i.e. deepcopy(defaults, mysettings).

**Comment by nnixaa** [comment]
@geneeblack now this should work as you described, you can pass the whole settings object with the changes you need and it will be merged on top of the default settings object.

**Comment by jkon** [comment]
If I am understanding this right, you are only talking about when you pass the settings object into the component in the view template. What if I wanted to make a change to the table with a settings property after the view is rendered? For example, if I have a button bound to a function in my component that I want to hide the sub header, would I do it like this:
toggleSubHeader() {
    console.log('you toggled the sub header');
    this.settings.hideSubHeader = !this.settings.hideSubHeader;
  }

or do I need to then pass the settings into the smart table component again somehow?

**Comment by legrosbill** [comment]
@jkon Hi, have the same question, this way don't seems to work for me , have you find a solution ?

**Comment by legrosbill** [comment]
unfortunately, you have to change this.settings to trigger onChanges event (it's a global angular2 binding issue)
so the right way is  :
toggleSubHeader() {
console.log('you toggled the sub header');
this.settings = {
    hideSubHeader:!this.settings.hideSubHeader
};
}

**Comment by jkon** [comment]
I had a lot of other customizations that I wanted to do with this package so I made a copy of the repo locally and exposed the initGrid() function. Probably not smartest way, but it allows me to make all the changes I want.

**Comment by kmanship** [comment]
Not a fan of this approach as it involves jQuery, but use jQuery to find the smart filters and wire up a button to trigger the toggle.

```
  public toggleFilter() {
    const filterRow = this.$('.ng2-smart-filters');
    this.hideSubHeader = !this.hideSubHeader;
    this.hideSubHeader ? filterRow.hide() : filterRow.show();
  }
```
