### ISSUE TITLE
disable cell in edit mode

### ISSUE THREAD

**Issue by Elhamo** [akveo/ng2-smart-table#191]
Hi, could you please tell me how to disable a cell when edit action is clicked. 
Thanks.

**Comment by Elhamo** [comment]
just added editable:false like this:

 columns: {
      handle: {
        title: 'Handle',
        editable: false,
      },

**Comment by nextsoftpl** [comment]
what if I would like to disable a particular row from edit, but not show the edit/delete buttons?

**Comment by charleswrayjr** [comment]
The problem with this is it still shows the field as editable, it just does not allow editing. This can be very confusing to the end user in a large scale deployment without training. Is there a way to not show the columns that cannot be edited as inputs?

**Comment by gfaganli** [comment]
+ also need to hide action column at all

**Comment by Naik-Akshay** [comment]
how to disabled edit to whole cell and allow only particular row
