### ISSUE TITLE
I want to add an icon inside action of every row?  

### ISSUE THREAD

**Issue by sudhirroy-tudip** [akveo/ng2-smart-table#197]
Hi,
First I  Congratulate to all of your team by giving such a nice smart table feature. We already implement it in lots of websites. Now, I was stuck in a simple problem. I want to use an icon (for sake of simplicity we call as View icon) in action column for each row. Also, I want to bind click event on it,  just like edit and delete which gives me data of that particular row. Please help me how can I achieve.

**Comment by TheMalloum** [comment]
Hi, 

+1

I just want to insert icon in a cell.

I use           
valuePrepareFunction : (cell, row) => { return "<span class='fa fa-users'></span>"; }
but it doesn't works.

**Comment by katestearns-suplari** [comment]
Did you find a solution for this?

**Comment by TheMalloum** [comment]
@katestearns-suplari  
Yes, I use : 

          color: {
            title: translate["COLOR"],
            filter: false,
            type: 'custom',
            renderComponent: ColorComponent,
          }

and the definition of ColorComponent is :

import { Component, OnInit, Input } from '@angular/core';
@Component({
  selector: 'carto-color',
  template: `<div class="carto-color-class" [style.background-color]="getColor()"> </div>`,
  styleUrls: ['./color.component.css']
})
export class ColorComponent implements  OnInit {
 @Input() value: string;
 constructor() { }
 ngOnInit() {}
  
getColor(){
    return this.value;
  }

}

**Comment by kasiselva** [comment]
i want to change background color for data row based on status type in "ng2-smart-table"
