### ISSUE TITLE
How to hide actions/filter row?

### ISSUE THREAD

**Issue by Deilan** [akveo/ng2-smart-table#203]
Is there a way to hide actions/filter row (the first after the `thead` and before data rows)?

**Comment by ManpreetSingh80** [comment]
set hideSubHeader to true in settings object to hide filter and add action row.

**Comment by gaikwadvaibhav** [comment]
settings = {
    hideSubHeader: true, // hide filter row 
    actions: false,  // hide action column
    .......
  };

**Comment by ezequiel88** [comment]
Is possible a button toggle for enable/disable the filter row?

**Comment by miguelleitevieira** [comment]
It's possible to change the table settings after the html be loaded?
I'm trying to disable conditionally after user add some data into the table, but the changes are not detected.
