### ISSUE TITLE
How to select row programmatically?

### ISSUE THREAD

**Issue by Deilan** [akveo/ng2-smart-table#204]
Is there a way to select row programmatically? As far as I can see, there's no API for it in `ng2-smart-table` component.

**Comment by LLIyRiK** [comment]
+1

**Comment by evgeny-o** [comment]
+1

**Comment by JrmyDev** [comment]
+1

**Comment by OrenciucEvghenii** [comment]
+1

**Comment by saywhatjames** [comment]
+1

**Comment by jopperknopper** [comment]
+1

**Comment by pg7812** [comment]
+1

**Comment by TaylorZaneKirk** [comment]
+1 really wish the devs would ever look at the issues...

**Comment by smasala** [comment]
+1

**Comment by smasala** [comment]
Trying to select a row with protractor, the event is fired... but the row is never actually selected.

**Comment by smasala** [comment]
Not quite programmatically but with protractor you have to `click()` the row twice, this is because `isSelected` in `selectRow() in data-set.ts` sets the flag `isSelected` incorrectly when `previousIsSelected` is in it's original state of `undefined`.

**Comment by gravypower** [comment]
a bit hacky but you could alter the workaround in issue https://github.com/akveo/ng2-smart-table/issues/235 by adding the row you wish to select to the list that is used to hold the selected items.

**Comment by DependencyHell** [comment]
maybe something like this :

```
this.table.grid.getRows().forEach((row) => {
    this.table.grid.selectRow(row);
    //or :
    this.table.grid.multipleSelectRow(row);
});
```

**Comment by oriand** [comment]
@DependencyHell  is that worked for you? I am not able to register Ng2SmartTableComponent. I am using import { Ng2SmartTableModule } from 'ng2-smart-table';

**Comment by de-mim-1974** [comment]
@oriand get it by 
`import { Ng2SmartTableComponent } from 'ng2-smart-table/ng2-smart-table.component';`
the code from @DependencyHell runs now, but don't help me. (The row have isSelected=true, but don't set the 'selected' value at class element - `class="ng2-smart-row selected"`)

**Comment by sharath1608** [comment]
Although it's a hack and I wouldn't recommend the following if there was a better way but I was desperate and it works.

```
      setTimeout(() => {
        let element: HTMLElement = document.querySelectorAll('ng2-smart-table table tbody tr')
          .item(idx)
          .querySelector('td')as HTMLElement;
        element.click();
      },200);
```
This sets the CSS styles and also ensures the table grid data is marked selected.
Here's the [stackblitz](https://stackblitz.com/edit/angular-oaczfv).

**Comment by ClemAnto** [comment]
> maybe something like this :
> 
> ```
> import {ViewChild} from '@angular/core';
> import {Ng2SmartTableComponent} from 'ng2-smart-table/ng2-smart-table.component';
> ...
> 
> @ViewChild('table') table: Ng2SmartTableComponent;
> 
> ...
> 
> myFunction() {
>   this.table.grid.getRows().forEach((row) => {
>       this.table.grid.selectRow(row);
>       //or :
>       this.table.grid.multipleSelectRow(row);
>   });
> }
> ```
> 
> set a name to the table :
> 
> ```
> <ng2-smart-table #table [settings]="settings" [source]="source">
> </ng2-smart-table>
> ```

For version > 1.4.0 you have to replace your Ng2SmartTableComponent import with:

`import { ɵbo as Ng2SmartTableComponent } from 'ng2-smart-table';`

https://github.com/akveo/ng2-smart-table/issues/1055#issuecomment-563971309
