### ISSUE TITLE
count not working !

### ISSUE THREAD

**Issue by amineparis** [akveo/ng2-smart-table#216]
when I use localDatasource count It show.` function () { return this.filteredAndSorted.length; }` instead of the number of rows

**Comment by LexZhukov** [comment]
Hi @amineparis. Could you provide an example with this bug on [plunker](https://plnkr.co)?

**Comment by amineparis** [comment]
I don't track any event I have just defined a getter 
```
 get count(){
    return this.smartTableData.count
  }
```

and I get that issue when I use {{count}} in templates

**Comment by amineparis** [comment]
I solver the issue by using count() instead of count :(

**Comment by RoryGarner92** [comment]
Can you explain how you solved this with an example ?

**Comment by ak-chinmay** [comment]
@amineparis I am having the same issue can you please elaborate how you solved this

**Comment by lickybuay** [comment]
@ak-chinmay In my example:

this.source = new LocalDataSource();
this.source.load(this.myservice.myFunction()); //Load the table

console.log( this.source.count() ); //Show Count value

**Comment by ak-chinmay** [comment]
Got it thanks, @lickybuay  :)

**Comment by MerkulovDev** [comment]
for me this.source.count() return 0
x-total-count value from server is more then 300 000
also pagination is not shows. i got only that result length is in request param.

with exampe in documentation all works correctly.
