### ISSUE TITLE
TypeError: this.inputControl.valueChanges.distinctUntilChanged is not a function

### ISSUE THREAD

**Issue by github20130710** [akveo/ng2-smart-table#229]
when I import ng2smarttable in my module, run it, then got this error: 

![image](https://cloud.githubusercontent.com/assets/4979224/24027767/ef5d7dc4-0b04-11e7-8f80-8d5aa6385b5c.png)

 what causes it and how to fixes it ? Can anyone help me with this issue ? Thanks !

**Comment by pervasive-falcon** [comment]
The relevant files need to import that function from rxjs, using: 

`import 'rxjs/add/operator/distinctUntilChanged';`

Could anyone please look into this?

**Comment by bmstambaugh** [comment]
@pervasive-falcon adding the import to the input-filter.component.js file got rid of the error.
