### ISSUE TITLE
Default settings extended

### ISSUE THREAD

**Issue by geneeblack** [akveo/ng2-smart-table#23]
I propose changing the value passed to deepextend to be a copy of the defaultSettings rather than a reference to the defaultSettings, this isolates and decouples the current defaultSettings values and prevents the additional properties being added in the extend from being included in the defaultSettings when it is reused in the future.

from
https://github.com/akveo/ng2-smart-table/blob/master/src/ng2-smart-table/ng2-smart-table.component.ts#L181

change
return deepExtend({}, this.defaultSettings, this.settings);

to
return deepExtend({}, JSON.parse(JSON.stringify(this.defaultSettings)), this.settings);

**Comment by nnixaa** [comment]
Hey @geneeblack, thanks for proposal. Sorry, don't have time to check at the moment, but are you sure that the first line doesn't clone the object and affects the defaultSettings then?

**Comment by geneeblack** [comment]
It looks like the changes that were made 

**return deepExtend({}, this.defaultSettings, this.settings);**

does the job, I was looking at old code and used new code in my example

the old code that I was looking at was

**return deepExtend(this.defaultSettings, this.settings);**

which was extending the default settings, cloning was overkill but would have isolated the original default settings
