### ISSUE TITLE
Module not found (Angular 4.0.0-rc.5)

### ISSUE THREAD

**Issue by petrskalicka** [akveo/ng2-smart-table#238]
I just update to latest angular 4.0.0-rc.5 and get this error:
`ERROR in ./~/ng2-smart-table/src/ng2-smart-table/lib/data-source/server/server.data-source.ts`
`Module not found: Error: Can't resolve '@angular/http/src/url_search_params' in '/Users/Petik/Sites/fpm/frontend/node_modules/ng2-smart-table/src/ng2-smart-table/lib/data-source/server'`
`@ ./~/ng2-smart-table/src/ng2-smart-table/lib/data-source/server/server.data-source.ts 12:0-70`
 `@ ./~/ng2-smart-table/src/ng2-smart-table/lib/index.ts`
 `@ ./~/ng2-smart-table/ng2-smart-table.js`
 `@ ./src/app/clients/clients.module.ts`
 `@ ./src/app/app.module.ts`
 `@ ./src/main.ts`
 `@ multi webpack-dev-server/client?http://localhost:4201 ./src/main.ts`

I have to update server.data-source.ts in order to work.
From:
`import { RequestOptionsArgs } from '@angular/http/src/interfaces';`
` import { URLSearchParams } from '@angular/http/src/url_search_params';`

To:
`import { URLSearchParams, RequestOptionsArgs } from '@angular/http';`

**Comment by CanKer** [comment]
I had the same problem, thanks @petrskalicka

**Comment by rockcoolt** [comment]
@petrskalicka Thank !

**Comment by SteamWind** [comment]
It needs a push

**Comment by LexZhukov** [comment]
Try to update to latest ng2-smart-table version.

**Comment by tobemedia** [comment]
npm install --save ng2-smart-table@latest 
solved the problem for me

**Comment by thinhlx1993** [comment]
many thanks @petrskalicka

**Comment by gierg** [comment]
@lexzhukov : i'm still get module not found, when i update ng2-smart-table version to the latest

**Comment by Slavrix** [comment]
considering this post is from 10 months ago, its probably worth posting some new information about our current environment that your using for this also.

**Comment by SteamWind** [comment]
I lived this rep to Primeng. Primeng is a set of modules containing really smart tables.

**Comment by nagipogu** [comment]
ERROR in src/app/app.module.ts(4,37): error TS2307: Cannot find module 'ng2-smart-table'.

i ｢wdm｣: Failed to compile.
^CTerminate batch job (Y/N)? y
PS D:\I-AAA\Projects\Giribabu\IAAAtech\Projects\JOHNDEERE\john-deere3\ng2-smart-table> npm install --save ng2-smart-table@latest
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "ng2-smart-table" under a package
npm ERR! also called "ng2-smart-table". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Intel\AppData\Roaming\npm-cache\_logs\2019-02-04T13_21_55_023Z-debug.log
