### ISSUE TITLE
Deletion of onAdd, onEdit, onDelete, onCreate, onSave, onCancelEdit

### ISSUE THREAD

**Issue by Deilan** [akveo/ng2-smart-table#243]
@LexZhukov @damnko Why did you remove `onAdd`, `onEdit`, `onDelete`, `onCreate`, `onSave`, `onCancelEdit`? How it is supposed to intercept events in `inline` mode - e.g. to handle saving logic?

**Comment by damnko** [comment]
Hi @Deilan, could you elaborate more on the issue you are experiencing?

**Comment by Deilan** [comment]
@damnko The issue I've experienced was just because of code in our fork, which interfered with the code from the upstream (your) repository that I recently pulled in. Anyway, I've managed it out. Sorry for disturbance!
