### ISSUE TITLE
How to disable EDIT button only for first row.

### ISSUE THREAD

**Issue by aadgithub** [akveo/ng2-smart-table#247]
I am using smart table.I have displayed data in table from JSON.I want to disable EDIT button for first row only.I have used ng-repeat to display data in table.

**Comment by mfsi-surajs** [comment]
Did you find any workaround?

**Comment by aadgithub** [comment]
yes,use $index, $first, $middle, $last, $even, $odd of ngRepeat statement for specific rows.
I used $first for first row.

**Comment by mfsi-surajs** [comment]
@aadgithub  If you could show some code that will be helpful.

**Comment by aadgithub** [comment]
`<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.23/angular.min.js"></script>
<div ng-app="app" ng-controller="myCtrl">
  <table>
    <tr ng-repeat="friend in friends">
      <td>
        {{$index}}
      </td>
      <td>
        <button ng-disabled="$first">test</button>
      </td>
    </tr>
  </table>
</div>`

**Comment by aadgithub** [comment]
angular.module("app", []).controller("myCtrl", function($scope) {
  $scope.friends = [{
      name: 'John',
      age: 25,
      gender: 'boy'
    },
    {
      name: 'Jessie',
      age: 30,
      gender: 'girl'
    },
    {
      name: 'Johanna',
      age: 28,
      gender: 'girl'
    },
    {
      name: 'Joy',
      age: 15,
      gender: 'girl'
    }
  ]
});


<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.23/angular.min.js"></script>
<div ng-app="app" ng-controller="myCtrl">
  <table>
    <tr ng-repeat="friend in friends">
      <td>
        {{$index}}
      </td>
      <td>
        <button ng-disabled="$first">test</button>
      </td>
    </tr>
  </table>
</div>

**Comment by aadgithub** [comment]
https://stackoverflow.com/questions/42993492/in-angular-smart-table-how-to-disable-edit-functionality-for-one-row?noredirect=1#comment73077542_42993492
