### ISSUE TITLE
Demo Source of Custom editor/renderer column type doesn't open

### ISSUE THREAD

**Issue by srtijolo** [akveo/ng2-smart-table#248]
I'm trying to navigate to this link below, and I'm being redirected to there after clicking on the Demo Source of the 'Custom editor / renderer column type' and I'm getting 404

https://github.com/akveo/ng2-smart-table/blob/master/demo/src/app/pages/demo/components/advanced-example-custom-editor.component.ts

**Comment by srtijolo** [comment]
I've noticed that all links of Demo's Demo Source on https://akveo.github.io/ng2-smart-table/demo are broken

**Comment by Rjongenburger** [comment]
+1

**Comment by skysoftdev** [comment]
https://github.com/akveo/ng2-smart-table/tree/943ce55125a003c1ee1f61a0bc92ad728b46ee34/src/app/pages/examples
Here all sources
