### ISSUE TITLE
Server Pagination

### ISSUE THREAD

**Issue by csepmdat** [akveo/ng2-smart-table#25]
Hi all,

Do we have anyway to server loading data when change page. Because I have a situation with a large amount of items, I think it should be loaded dynamic when user change page.

Thanks.

**Comment by hoswey** [comment]
it seems this issue same with #30

**Comment by nnixaa** [comment]
Closing as duplicate, more info here https://github.com/akveo/ng2-smart-table/issues/30#issuecomment-256367167

**Comment by jeevitha8123** [comment]
I'm trying to add total record count fetched from my first API call when the page loads initially. Based on the count I will come to know the total number of pages, and in turn based on the page click will fire appropriate API calls to populate data. Is this possible using NG2-Smart-Table?

**Comment by jeevitha8123** [comment]
Do we have anyway to server loading data when change page. Because I have a situation with a large amount of items, I think it should be loaded dynamic when user change page. expecting code in ng2 smart table using angular and typescript....

**Comment by sneha1302** [comment]
@jeevitha8123 Were you able to find a solution to your question ?
