### ISSUE TITLE
Build error - Module not found

### ISSUE THREAD

**Issue by Ezeon** [akveo/ng2-smart-table#251]
Hi. I followed the installation guide lines, but I get the following errors when building. All the files does existing in the correct folder. Angular version is 2.4.9. Package.json file is attached.

ERROR in ./~/ng2-smart-table/src/ng2-smart-table/ng2-smart-table.component.ts
Module not found: Error: Can't resolve 'ng2-smart-table.scss' in 'C:\dev\ndd\node_modules\ng2-smart-table\src\ng2-smart-table'
 @ ./~/ng2-smart-table/src/ng2-smart-table/ng2-smart-table.component.ts 204:21-52
 @ ./~/ng2-smart-table/ng2-smart-table.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/ng2-smart-table/src/ng2-smart-table/ng2-smart-table.component.ts
Module not found: Error: Can't resolve 'ng2-smart-table.html' in 'C:\dev\ndd\node_modules\ng2-smart-table\src\ng2-smart-table'
 @ ./~/ng2-smart-table/src/ng2-smart-table/ng2-smart-table.component.ts 205:22-53
 @ ./~/ng2-smart-table/ng2-smart-table.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/ng2-smart-table/src/ng2-smart-table/components/filter/filter.component.ts
Module not found: Error: Can't resolve 'filter.scss' in 'C:\dev\ndd\node_modules\ng2-smart-table\src\ng2-smart-table\components\filter'
 @ ./~/ng2-smart-table/src/ng2-smart-table/components/filter/filter.component.ts 54:21-43
 @ ./~/ng2-smart-table/src/ng2-smart-table.module.ts
 @ ./~/ng2-smart-table/ng2-smart-table.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/ng2-smart-table/src/ng2-smart-table/components/pager/pager.component.ts
Module not found: Error: Can't resolve 'pager.scss' in 'C:\dev\ndd\node_modules\ng2-smart-table\src\ng2-smart-table\components\pager'
 @ ./~/ng2-smart-table/src/ng2-smart-table/components/pager/pager.component.ts 95:21-42
 @ ./~/ng2-smart-table/src/ng2-smart-table.module.ts
 @ ./~/ng2-smart-table/ng2-smart-table.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

[package.json.txt](https://github.com/akveo/ng2-smart-table/files/870732/package.json.txt)
[error.txt](https://github.com/akveo/ng2-smart-table/files/870735/error.txt)
Update: added the error messages in a text file to avoid formating issues with the text editor.

**Comment by maheshp212** [comment]
I am also getting the similar error please help

**Comment by Ezeon** [comment]
I found the issue. Some file paths are missing ./ at the start.

For example in ng2-smart-table.component.ts

@Component({
  selector: 'ng2-smart-table',
  styleUrls: ['ng2-smart-table.scss'],
  templateUrl: 'ng2-smart-table.html'
})

Changing this to the following resolves the problem:

@Component({
  selector: 'ng2-smart-table',
  styleUrls: ['./ng2-smart-table.scss'],
  templateUrl: './ng2-smart-table.html'
})

The same works for filter.component.ts and pager.component.ts. Fixing these four paths resolves the issue for me.

This should probably be a pull request, unless I'm missing something obvious.

**Comment by Ezeon** [comment]
I see that this has already been fixed in the master branch.

Following the installation guide and running 'npm install --save ng2-smart-table' actually installs version 0.6.0-1, which will not run because of this bug. I guess this will start working again when the next release is pushed to npm.
