### ISSUE TITLE
New column created from Object datatype

### ISSUE THREAD

**Issue by SantaUA** [akveo/ng2-smart-table#254]
Hello. This will be sound more like question than issue. So sorry in advance for posting this here 
How I able to create new column with value from Object ?
Code of my setting and data below for more clearly understanding
private settings = {
```
columns: {
      firstName: {
        title: 'First name',
        type: 'text'
      },
      lastName: {
        title: 'Last name',
        type: 'text'
      },
      userType: {  
        // This is correct way only when there is string in response from API named - userType
        // But when I'm trying to type something like - userType.value i get an error 
        title: 'User type',
        type: 'text'
      },
}
```
data from API: 
```
.......
    {
      firstName: 'Jacob',
      lastName: '',
      middleName: '',
      userType: {value: 'superAdmin', display: 'Super Administrator'},
      login: '',
      password: '',
      phoneNumber: '066-233-77-34',
      city: 'Roma',
      address: 'someStreet',
      salary: '0',
    },
......
```

**Comment by KostyaDanovsky** [comment]
@SantaUA, you could look at this issue: https://github.com/akveo/ng2-smart-table/issues/11

**Comment by SantaUA** [comment]
@KostyaDanovsky how could i use it in my case with data-binding to one of property of my Object ? Because in case #11 situation when property get checked

**Comment by SantaUA** [comment]
@KostyaDanovsky The night brings counsel :relaxed:
I got an idea invoke `myCustomFunc ` in `valuePrepareFunction`. By `myCustomFunc ` I parse value and return what should be

**Comment by ehdwns980416** [comment]
Can you share code?

**Comment by SantaUA** [comment]
@ehdwns980416 do still need the code ?

**Comment by yadoble** [comment]
@SantaUA could you share the code?

**Comment by SantaUA** [comment]
@yadoble sure
` 
private settings = {
    hideHeader: true,
    columns: {
      EntryDate: {
        title: 'Date',
        type: 'text',
        valuePrepareFunction: (value) => {
          return this.transformDate(value);
        },
        filterFunction: (value, search) => {
          let match = this.transformDate(value).indexOf(search) > -1
          if (match || search === '') { return true; }
          else { return false; }
        }
      }
}
`
methods:
`
  transformDate(value) {
    let newValue;
    newValue = this.datePipe.transform(value, 'dd.MM.yyyy');
    return newValue;
  }
`

Here is are a few important things:
- valuePrepareFunction() change value for for view on html
- filterFunction() for working filter after value was changed
Why ? because ngSmartTable filter will sort column by value from your js code, not for view data
Exp: if you will have data by ID and change view to name be ID(ID: 1 will be changed to NY) filter will working by ID not the view data if you won't use the custom filter func
