### ISSUE TITLE
Button in table row.

### ISSUE THREAD

**Issue by Rjongenburger** [akveo/ng2-smart-table#256]
Hello,

I want to add a button in each row of a column, so when it's clicked, it will go to a new page.
I am not sure how to do this.
Can someone help?

`<button type="button">Click me!</button>`

**Comment by MeindertRomkes** [comment]
What was the solution?

**Comment by Rjongenburger** [comment]
I used a different approach. 
`      example: {
        title: 'Buttons',
        type: 'html',
        filter: false,
        valuePrepareFunction: (cell,row) => {
          return `<a href="/#/pages/tables/buttons/${row.id}">Buttons</a>`;
        },
        editable: false
      },
`

But you can also accomplish it by making a custom render component and making a button in the template with routerlink.  
[CustomRenderComponent](https://github.com/akveo/ng2-smart-table/blob/332f7fc13ebf40b20c5723c3f6f65f3bb46f036f/src/app/pages/examples/tables/custom-render.component.ts)

**Comment by shubhamgupta28** [comment]
If you are still looking for a holistic answer, maybe this can help you. 
https://plnkr.co/edit/OtJI13uA89caf8TG5lbI?p=preview

**Comment by serdanilov** [comment]
```
return <a href="/#/pages/tables/buttons/${row.id}">Buttons</a>;
},
```
this just doesn't work for me, ${row.id} isn't interpolated anyhow..
