### ISSUE TITLE
Add link in each row of a column with row object variable

### ISSUE THREAD

**Issue by Rjongenburger** [akveo/ng2-smart-table#257]
Hello,

I want to add a link in each row of a column, and when it's clicked, it will go to a new page. For that I need to get a variable of that rows object.
I am not sure how to do this.
Can someone help?

I tried this, but it doesn't work. 

` opcodes: {

        title: 'Opcodes',

        editable: false,

        type: 'html',

        valuePrepareFunction:(cell,row)=>{

          return `<a title="See opcodes onClick="onOpcodesClick(row)>Opcodes</a> 
      },`

**Comment by d7laungani** [comment]
what did you do to fix this?
