### ISSUE TITLE
ServerDataSource & Elastic Search

### ISSUE THREAD

**Issue by AustinGHoward** [akveo/ng2-smart-table#261]
I am attempting to populate my smart table using the ServerDataSource, that calls an endpoint, which effectively returns a JSON object. While I am defining the "dataKey" where the actual object I need from the response, I am having difficulty configuring the column key settings. 

Since, the data I am looking for is nested within the JSON object, how would I handle naming the proper column keys?

I have tried a few things related to fully qualifying the object name (hits.hits._source.invdate) but that is not working. Any help would be greatly appreciated!

**Comment by hgarc014** [comment]
@AustinGHoward  did you end up solving this issue?
