### ISSUE TITLE
ERROR in ./~/ng2-smart-table/src/ng2-smart-table/lib/data-source/server/server.data-source.ts

### ISSUE THREAD

**Issue by st-clair-clarke** [akveo/ng2-smart-table#263]
Hi,
I am using the current release of ng2 for angular4. I am getting the following using the command ng serve

ERROR in ./~/ng2-smart-table/src/ng2-smart-table/lib/data-source/server/server.data-source.ts
Module not found: Error: Can't resolve '@angular/http/src/url_search_params' in 'J:\workspace\angular2\ts\ep
imss\node_modules\ng2-smart-table\src\ng2-smart-table\lib\data-source\server'
 @ ./~/ng2-smart-table/src/ng2-smart-table/lib/data-source/server/server.data-source.ts 12:0-70
 @ ./~/ng2-smart-table/src/ng2-smart-table/lib/index.ts
 @ ./~/ng2-smart-table/ng2-smart-table.js
 @ ./shared/shared.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

First time seeing this error. Thanks for your help.

**Comment by Bengejd** [comment]
Try updating to the latest version of ng2-smart-table. You might still be on 0.5.#

**Comment by st-clair-clarke** [comment]
Thanks. Worked
