### ISSUE TITLE
Module not found: Error: Can't resolve 'ng2-completer'

### ISSUE THREAD

**Issue by vvandoorne** [akveo/ng2-smart-table#270]
Got this error after install/save ng2-smart-table version 1.0.1.  Module not found: Error: Can't resolve 'ng2-completer'.

We added ng2-completer as a dependency to get it to compile successfully.  This resolved the issue.  
We just wanted to bring it to your attention. 

npm install ng2-completer --save-dev

**Comment by LexZhukov** [comment]
@vvandoorne it's ok. You need to install ng2-completer.

**Comment by vvandoorne** [comment]
Thanks LexZhukov.

**Comment by almgwary** [comment]
### Solved
```
npm i rxjs-compat --save
npm i ng2-completer --save

```

**Comment by YohanKulasinghe** [comment]
still the error occur after doing all the thing mention here 
with ng2-smart-table version 1.6

**Comment by solomon911** [comment]
> still the error occur after doing all the things mention here
> with ng2-smart-table version 1.6

use v1.5, there were some changes made in v1.6 that made it compatible to angular 9 and this is causing the issue.

**Comment by usamakhalil86** [comment]
Tried above all but stil has issue . even switching to v1.5 does not work.

- Using Angular 7 with smart table v1.5/1.6


ERROR in node_modules/ng2-smart-table/lib/components/cell/cell-editors/completer-editor.component.d.ts(2,34): error TS2307: Cannot find module '@akveo/ng2-completer'.
node_modules/ng2-smart-table/lib/components/filter/filter-types/completer-filter.component.d.ts(3,34): error TS2307: Cannot find module '@akveo/ng2-completer'.
node_modules/ng2-smart-table/lib/components/tbody/tbody.component.d.ts(29,9): error TS1086: An accessor cannot be declared in an ambient context.

**Comment by solomon911** [comment]
@usamakhalil86 can u try delete node modules folder and execute `npm install` and check?

**Comment by svzi** [comment]
@solomon911 I'm experiencing the same issue as @usamakhalil86 ! I'm using Angular 7.2.x with `ng2-smart-table` version 1.6.0 and `ng2-completer` version 9.0.1.

I've also tried to downgrade to version 1.5.0 of `ng2-smart-table` but that doesn't help either:
```
[ng] ERROR in node_modules/ng2-completer/src/components/completer-cmp.d.ts(54,9): error TS1086: An accessor cannot be declared in an ambient context.
[ng] node_modules/ng2-completer/src/components/completer-cmp.d.ts(55,9): error TS1086: An accessor cannot be declared in an ambient context.
[ng] node_modules/ng2-completer/src/components/completer-cmp.d.ts(56,9): error TS1086: An accessor cannot be declared in an ambient context.
[ng] node_modules/ng2-completer/src/components/completer-cmp.d.ts(57,9): error TS1086: An accessor cannot be declared in an ambient context.
[ng] node_modules/ng2-completer/src/components/completer-cmp.d.ts(65,9): error TS1086: An accessor cannot be declared in an ambient context.
[ng] node_modules/ng2-completer/src/components/completer-cmp.d.ts(66,9): error TS1086: An accessor cannot be declared in an ambient context.
[ng] node_modules/ng2-completer/src/components/completer-cmp.d.ts(67,9): error TS1086: An accessor cannot be declared in an ambient context.
[ng] node_modules/ng2-completer/src/directives/ctr-completer.d.ts(42,9): error TS1086: An accessor cannot be declared in an ambient context.
[ng] node_modules/ng2-completer/src/directives/ctr-completer.d.ts(43,9): error TS1086: An accessor cannot be declared in an ambient context.
[ng] node_modules/ng2-completer/src/directives/ctr-completer.d.ts(44,9): error TS1086: An accessor cannot be declared in an ambient context.
[ng] node_modules/ng2-completer/src/directives/ctr-completer.d.ts(45,9): error TS1086: An accessor cannot be declared in an ambient context.
[ng] node_modules/ng2-completer/src/directives/ctr-completer.d.ts(46,9): error TS1086: An accessor cannot be declared in an ambient context.
[ng] node_modules/ng2-completer/src/directives/ctr-input.d.ts(27,9): error TS1086: An accessor cannot be declared in an ambient context.
[ng] node_modules/ng2-completer/src/directives/ctr-input.d.ts(28,9): error TS1086: An accessor cannot be declared in an ambient context.
[ng] node_modules/ng2-completer/src/directives/ctr-list.d.ts(32,9): error TS1086: An accessor cannot be declared in an ambient context.
[ng] node_modules/ng2-completer/src/directives/ctr-list.d.ts(33,9): error TS1086: An accessor cannot be declared in an ambient context.
[ng] node_modules/ng2-completer/src/directives/ctr-row.d.ts(13,9): error TS1086: An accessor cannot be declared in an ambient context.
[ng] node_modules/ng2-completer/src/directives/ctr-row.d.ts(14,9): error TS1086: An accessor cannot be declared in an ambient context.
```

Any help would be really much appreciated.

**Comment by svzi** [comment]
I got it working by myself: I've downgraded `ng2-completer` from version 9.0.1 to version 3.0.2!

**Comment by usamakhalil86** [comment]
I removed the git source code and downloaded again . Rum npm install and it
worked.

**Comment by chadirahme** [comment]
Hi usamakhalil86
I face the same issue!!
What the git source you removed? then download ng2-completer?

**Comment by brian-ndungu** [comment]
Finally figured it out. Was experiencing the same issue as you. You need to delete both ng2-completer and ng2-smart-table from your node modules folder then install the following versions:
`npm i ng2=completer@3.0.2` and `npm i ng2-smart-table@1.5.0` 
it should work after that.

> Hi usamakhalil86
> I face the same issue!!
> What the git source you removed? then download ng2-completer?

**Comment by lucasglobalsys** [comment]
**For Angular 9+ try this:**

in your **tsconfig.app.json**, set  

```
 "angularCompilerOptions": {
    "enableIvy": true
  }
```

its worked for me, with @akveo/ng2-completer dependency only.

**Comment by rahianeja** [comment]
`npm i @akveo/ng2-completer`

This worked for me +1 +1 +1

**Comment by vijayravii** [comment]
do : npm i
worked for me.
