### ISSUE TITLE
Getting Compilation errors in ng2-smart-table 1.0.1 with angular 4.0.0 and cli 1.0.0

### ISSUE THREAD

**Issue by PrazSam** [akveo/ng2-smart-table#275]
Hi, 
Can you please help me on this error i got after updating to latest ng2-smart-table

## ERROR
ERROR in Error encountered resolving symbol values statically. Could not resolve ng2-completer relative to ..Proj dir../node_modules/ng2-smart-table/components/cell/cell.module.d.ts., 
resolving symbol CellModule in ..Proj dir../node_modules/ng2-smart-table/components/cell/cell.module.d.ts, 
resolving symbol CellModule in ..Proj dir../node_modules/ng2-smart-table/components/cell/cell.module.d.ts

ERROR in ./~/ng2-smart-table/components/cell/cell.module.js
Module not found: Error: Can't resolve 'ng2-completer' in '..Proj dir..\node_modules\ng2-smart-table\com
ponents\cell'
 @ ./~/ng2-smart-table/components/cell/cell.module.js 10:0-51
 @ ./~/ng2-smart-table/ng2-smart-table.module.js
 @ ./~/ng2-smart-table/index.js
 @ ./src/app/home/home.module.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/ng2-smart-table/components/filter/filter.module.js
Module not found: Error: Can't resolve 'ng2-completer' in '..Proj dir..\node_modules\ng2-smart-table\com
ponents\filter'
 @ ./~/ng2-smart-table/components/filter/filter.module.js 10:0-51
 @ ./~/ng2-smart-table/ng2-smart-table.module.js
 @ ./~/ng2-smart-table/index.js
 @ ./src/app/home/home.module.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/ng2-smart-table/components/cell/cell-editors/completer-editor.component.js
Module not found: Error: Can't resolve 'ng2-completer' in '..Proj dir..\node_modules\ng2-smart-table\com
ponents\cell\cell-editors'
 @ ./~/ng2-smart-table/components/cell/cell-editors/completer-editor.component.js 21:0-49
 @ ./~/ng2-smart-table/components/cell/cell.module.js
 @ ./~/ng2-smart-table/ng2-smart-table.module.js
 @ ./~/ng2-smart-table/index.js
 @ ./src/app/home/home.module.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/ng2-smart-table/components/filter/filter-types/completer-filter.component.js
Module not found: Error: Can't resolve 'ng2-completer' in '..Proj dir..\node_modules\ng2-smart-table\com
ponents\filter\filter-types'
 @ ./~/ng2-smart-table/components/filter/filter-types/completer-filter.component.js 22:0-49
 @ ./~/ng2-smart-table/components/filter/filter.module.js
 @ ./~/ng2-smart-table/ng2-smart-table.module.js
 @ ./~/ng2-smart-table/index.js
 @ ./src/app/home/home.module.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

## My Package Json is here

{
  "name": "my-project",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "ng": "ng",
    "start": "ng serve --proxy-config=proxy.conf.json",
    "build": "ng build",
    "test": "ng test",
    "pree2e": "webdriver-manager update --standalone false --gecko false",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.0.0",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/flex-layout": "^2.0.0-rc.1",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/material": "^2.0.0-beta.2",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@types/jasmine": "^2.5.40",
    "@types/node": "^6.0.59",
    "core-js": "^2.4.1",
    "d3": "^4.7.3",
    "d3-v4-typings": "0.0.1",
    "hammerjs": "^2.0.8",
    "material-design-lite": "^1.3.0",
    "mydaterangepicker": "^1.0.17",
    "ng2-charts": "^1.5.0",
    "ng2-smart-table": "^1.0.1",
    "ngx-pipes": "^1.4.4",
    "rxjs": "^5.1.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "^1.0.0",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
  }
}

**Comment by lexzhukov** [comment]
@PrazSam install ng2-completer.

**Comment by PrazSam** [comment]
@lexzhukov Thanks a lot. I never thought it was a dependency which must be installed separately. In smart table v 0.6.0-1 it didn't ask so. 

Can I know about this change? I cannot find it in [release notes](https://github.com/akveo/ng2-smart-table/releases) as well. Thanks in advance.

**Comment by bmstambaugh** [comment]
I had the same issue and this resolved it. If there is a dependency I think it should be listed as such in the documentation.
