### ISSUE TITLE
Angular 4 and smart table

### ISSUE THREAD

**Issue by danaERadwin** [akveo/ng2-smart-table#281]
I upgraded my environment to use Angular 4 and installed ng2-smart-table (version 1.0.2) for the fist time. 
I still get the following error message when importing the package:

> 'ng-template' is not a known element

I will appreciate your help!

**Comment by pedrolucasoliva** [comment]
Go to node_modules\ng2-smart-table,
find, at windows bar the term: "ng-template" (or find by yourself).
It's will find 4 files: table.js, table.umd.js, custom-edit-component.js and custom-view-component.js).
Then, replace "ng-template" for just "template" (with out ") at each one.

Works for me.

**Comment by danaERadwin** [comment]
@pedrolucasoliva 
It did work, but shouldn't it work with the "ng-template"? after all it is an Angular4 selector.

**Comment by pedrolucasoliva** [comment]
It's Angular update problem. I saw here: https://github.com/primefaces/primeng/issues/2333

**Comment by danaERadwin** [comment]
@pedrolucasoliva  Thanks!!

**Comment by abhilasha-sase** [comment]
@pedrolucasoliva,in my  node_modules\ng2-smart-table there is no term like 'ng-template" n even m not finding it on windows bar too and i have got only 2 files which are  table.js, table.umd.js after npm installation.Need help for this badly.
thank you.

**Comment by nameisvick** [comment]
Hello i am new to angular4 . i am trying to install  npm install angular-2-data-table --save in my angular4 project its throwing errors .  please help me
