### ISSUE TITLE
Pass data to custom component

### ISSUE THREAD

**Issue by levisalarcon** [akveo/ng2-smart-table#282]
I need to pass data from my smart-table component but I don't know how to do it. Besides, The [example page ](https://github.com/akveo/ng2-smart-table/blob/master/demo/src/app/pages/examples/custom-edit-view/advanced-example-custom-editor.component.ts) for custom components isn't working.

[StackOverflow question for details](http://stackoverflow.com/questions/43200386/angular2-smart-tables-pass-data-to-custom-component)

**Comment by moirobin** [comment]
I think you are looking for this example :
[https://github.com/akveo/ng2-smart-table/blob/master/src/app/pages/examples/custom-edit-view/advanced-example-custom-editor.component.ts](url)

**Comment by hagerSelim7** [comment]
how you solve this problem ?

**Comment by levisalarcon** [comment]
> how you solve this problem ?
@hagerSelim7 sorry, this is an old thread and I don't really remember the solution anymore, you may look at the StackOverflow post, that might help you.
