### ISSUE TITLE
EditConfirm not getting values

### ISSUE THREAD

**Issue by Kresys** [akveo/ng2-smart-table#284]
Hi, I've a problem, when i validate the edit of my row, the $event send me only old object without any edits i could have done. Here is my code:

`
TS:
    
    private _listePreleveur: Preleveur[];
    private preleveur: Preleveur;

    errorMessage: string = null;

    // Paramètres d'affichage du tableau
    settings = {
        mode: 'inline', // inline|external|click-to-edit
        selectMode: 'single', // single|multi
        add: {
            addButtonContent: '<i class="material-icons">add_circle</i>',
            createButtonContent: '<i class="material-icons">check</i>',
            cancelButtonContent: '<i class="material-icons">cancel</i>',
            confirmCreate: true
        },
        edit: {
            editButtonContent: '<i class="material-icons">mode_edit</i>',
            saveButtonContent: '<i class="material-icons">check</i>',
            cancelButtonContent: '<i class="material-icons">cancel</i>',
            confirmSave: true
        },
        delete: {
            deleteButtonContent: '<i class="material-icons">delete_forever</i>',
            confirmDelete: true
        },
        columns: {
            nom: {
                title: 'Nom',
                type: 'text',
            },
            prenom: {
                title: 'Prénom',
                type: 'text',
            },
            codePrel: {
                title: 'Code préleveur',
                type: 'number'
            } // and other 16 columns
        pager: {
            display: true,
            perPage: 12
        }
    }

    editPreleveur(formDatas){
        console.log(formDatas.data); // show me the object without editing
    }`

HTML:
`<ng2-smart-table *ngIf="_listePreleveur!=null" 
                [settings]="settings" 
                [source]="_listePreleveur"
                (editConfirm)="editPreleveur($event)">
</ng2-smart-table>`

If anyone has an idea ... thanks !

**Comment by lexzhukov** [comment]
@Kresys if you want to get updated data, use (edit) event.

**Comment by Kresys** [comment]
Thanks for your help.
In fact the table change (I've changed the confirmSave to false too), but how can I handle the event to save datas ?
I'm trying this but it's not calling my function:
`<ng2-smart-table *ngIf="_listePreleveur!=null" 
                [settings]="settings" 
                [source]="_listePreleveur"
                (edit)="editPreleveur($event)">
</ng2-smart-table>`

**Comment by lexzhukov** [comment]
@Kresys you can try to add in `editPreleveur` this row  `this._listePreleveur.update(oldObject, updatedObject)`.

**Comment by Kresys** [comment]
It's what I was trying to, i just didn't understand how to access to the new datas. Finally i use newData and everything is good ! thanks for your help !
