### ISSUE TITLE
this.inputControl.valueChanges.distinctUntilChanged(...).debounceTime is not a function

### ISSUE THREAD

**Issue by bmicka** [akveo/ng2-smart-table#285]
How to solve this problem?
![image](https://cloud.githubusercontent.com/assets/20736144/24705834/dc68af14-1a0d-11e7-8e5e-410e3241a60a.png)

Some links from https://akveo.github.io/ng2-smart-table/#/examples/using-filters not work. 

Would you somewhere upload functional application? Then I run npm install / update, ng s - and go. These parts of code often doesn't work. Thanks.

**Comment by lexzhukov** [comment]
@bmicka thanks for bug report. Could you try to update ng2-smart-table via `npm i -S ng2-smart-table@latest`.

**Comment by bmicka** [comment]
Yes, this help! Thank you. Your smart table looks good.
