### ISSUE TITLE
How to publish a forked version

### ISSUE THREAD

**Issue by Deilan** [akveo/ng2-smart-table#287]
How do one publish a forked version of the ng2-smart-table as a different npm package? What steps should be done for that?

Before the latest updates there was an npm script `build:package`, which prepared the package for publishing to npm, but it is gone. What is a replacement?

**Comment by lexzhukov** [comment]
@Deilan you need to perform the following steps:
1. change package name in package.json from src/ng2-smart-table folder;
2. run `build:release`;
3. go to dist/ng2-smart-table folder in console;
4. run `npm publish`.
