### ISSUE TITLE
how the fuck can we define a custom style

### ISSUE THREAD

**Issue by amineparis** [akveo/ng2-smart-table#291]
FUUUUUUUUUUCK YOUUUU REPO ADMINS, CAN T YOU SEE THAT ALL USERS ARE STUCK WITH THIS FUCKING PLUGING LOOKING FOR A WAY TO ERASE YOUR FUCKING UGLY STYLE

**Comment by nnixaa** [comment]
Hi @amineparis, thanks for your kind words. Here you can find some information on how to style angular 2 components https://angular.io/docs/ts/latest/guide/component-styles.html.

**Comment by amineparis** [comment]
GO CHECK +10 open issues talking about the issue in this repo to understund what I am talking about

**Comment by nnixaa** [comment]
@amineparis, being serious, changing the styles of the components is a basic knowledge of angular 2 framework, moreover, please consider github issues as a place for bugs and feature requests and use http://stackoverflow.com for questions like that. 
Just so you know, this project is open source and distributed completely free with no obligations, so if you find it not suiting your needs you might consider switching to any other available opensource/paid library out there.
 
Considering your intensity and really being worried about your calmness I suggest you taking a look at this piece of code which successfully works:

```
:host /deep/ ng2-smart-table {
  .table > tbody > tr > td:first-child {
    text-align: left;
  }
}
```
More details on this you can find in the documentation I mentioned erlier.
Have a good day.

**Comment by amineparis** [comment]
you still don't understund what I am talking about. it fucks the build process to manually change node_modules code and no body is fun of forking.  do a favor anch delete that css from the base repo

**Comment by jkoutavas** [comment]
lol, dude. Learn to override css. There's no need to touch the module.

**Comment by siamcomm** [comment]
@nnixaa Beautiful! I have been battling with this thinking it was because of my webpack configuration.
I added your suggested SASS code to my components CSS file and altered it to be CSS only:

```CSS
:host /deep/ ng2-smart-table .table > tbody > tr > td:first-child {
    text-align: left;
}
```

It worked beautifully. Thanks for help.

**Comment by spilote72** [comment]
Hi guys,

I got the problem that @amineparis is talking about. Webpack css/sass loader complains about invalid token in a scss file of the module (see stack dump below). The error is caused by '/deep/'.

 I'm trying to find a way to ignore scss file since the css are available for packaging... Will let you know if I find the solution.

NOTE that the error occurs when building in prod environment, either during manual deploy, manual build or automatic build on TFS for example.


**STACK DUMP:**

EXEC(0,0): Error : Module parse failed: C:\MYAPP\node_modules\ng2-smart-table\components\filter\filter.component.scss Unexpected token (1:0)
    You may need an appropriate loader to handle this file type.
    | :host {
    |   .ng2-smart-filter {
    |     /deep/ {
        at Object.<anonymous> (C:\MYAPP\node_modules\ng2-smart-table\components\filter\filter.component.scss:73:7)
        at __webpack_require__ (C:\MYAPP\node_modules\ng2-smart-table\components\filter\filter.component.scss:20:30)
        at C:\MYAPP\node_modules\ng2-smart-table\components\filter\filter.component.scss:66:18
        at C:\MYAPP\node_modules\ng2-smart-table\components\filter\filter.component.scss:69:10
        at ContextifyScript.Script.runInContext (vm.js:35:29)
        at ContextifyScript.Script.runInNewContext (vm.js:41:15)
        at Object.runInNewContext (vm.js:93:38)
        at WebpackResourceLoader._evaluate (C:\MYAPP\node_modules\@ngtools\webpack\src\resource_loader.js:110:40)
        at Compilation.compilation.plugin (C:\MYAPP\node_modules\@ngtools\webpack\src\resource_loader.js:58:26)
        at Compilation.applyPluginsAsyncSeries (C:\MYAPP\node_modules\tapable\lib\Tapable.js:206:13)
C:\MYAPP\Cones.Portal.csproj(123,5): Error MSB3073: The command "node node_modules/webpack/bin/webpack.js --env.prod" exited with code 2.

1>Publish failed due to build errors. Check the error list for more details.

**Comment by ravinleague** [comment]
@amineparis  
Github is a repository that is being used by Men and Women from all parts of the world. Derogatory statements and Abusive words cannot be used here. This is a purely professional space! If you can't write a review/issue without using these words, you nede not post anything here!
