### ISSUE TITLE
valuePrepareFunction called multiple times [bug]

### ISSUE THREAD

**Issue by karangarg45** [akveo/ng2-smart-table#300]
If i am using valuePrepareFunction to return the value of a column then the function is getting called at intermittent intervals even thought the table has been initialized which is affecting the performance of the application.There are only 2 rows in my table.Initially i thought putting the console.log in the function might be the issue then i put the debugger in the chrome to check and the same thing is happening

**Comment by luisfavila** [comment]
Why was this closed?
It's happening the same to me. valuePrepareFunction is called every second or so. Wtf?

**Comment by Nik1990** [comment]
Why closed? I'have the some problem? With only mouse scroll the valuePrepareFunction() is re-called and with this the page is slow.
