### ISSUE TITLE
requestElements().map().toPromise() is not a function in Angular 4

### ISSUE THREAD

**Issue by crossRT** [akveo/ng2-smart-table#304]
Actually, this error happened on latest ng2-admin which using Angular 4.0.1.
seems like `toPromise()` already removed from angular/http. 

adding `import 'rxjs/add/operator/toPromise';` in `server.data-source.ts` will solve this issue.

**Comment by ameagol** [comment]
server.data-source.ts or server.data-source.d.ts ?

**Comment by lexzhukov** [comment]
@crossRT thanks for bug report. Could you try to install the 1.0.4 version of the ng2-smart-table. This bug is fixed.

**Comment by crossRT** [comment]
@lexzhukov yeah, It's fixed. Thanks ya. =D
