### ISSUE TITLE
Default value for fields for add new?

### ISSUE THREAD

**Issue by Ezeon** [akveo/ng2-smart-table#310]
Is there a way of prefilling fields with default values when pressing 'add new?

**Comment by Ezeon** [comment]
I could not find any existing way to do this, so I created PR #311 to add this functionality.

**Comment by Ezeon** [comment]
Closing the issue as PR has been merged.

**Comment by hope4555** [comment]
columns: {
      name: {
        title: 'name',
        type: 'string',
        defaultValue: "123"
      }
}

**Comment by wattazoum** [comment]
Hi

Thank you for this functionality.

Is it possible to update the documentation with that ?
