### ISSUE TITLE
Setting column width is invalid

### ISSUE THREAD

**Issue by homx** [akveo/ng2-smart-table#316]
Hi
I am using the 1.0.4 version, I would like to set the width of the column, but did not work, can help me?
@lexzhukov 
Thank you in advance!

**Comment by lexzhukov** [comment]
@homx I published a new version of ng2-smart-table. Try to update to v1.1.0.

**Comment by homx** [comment]
OK,Thank yous

**Comment by fabryx92** [comment]
Setting the width for a column doesn't work for me. I'm using the v1.1.0.

**Comment by drsherlock** [comment]
I am also using v1.1.0 but the width is not working. The width does show in the styles but still it does not have any effect on the column.
