### ISSUE TITLE
Custom Range Filter with attribute of component

### ISSUE THREAD

**Issue by cgebe** [akveo/ng2-smart-table#321]
I want to setup a custom range filter and filter the data, where the grade is smaller than a component attribute. When i set up the filter like this, the data is not filtered. However when i output the result of the comparison it prints the right value for each comparison. (`this.limit` is a number)
```
this.source.setFilter([
    {
        field: 'grade',
        search: query,
        filter: (value: string, search: string) => {
            return parseFloat(value) <= this.limit;
        }
    }
], false);
```
When i input the search string via an input field it works and the data gets filtered:
```
this.source.setFilter([
    {
        field: 'grade',
        search: query,
        filter: (value: string, search: string) => {
            return parseFloat(value) <= parseFloat(search);
        }
    }
], false);
```

What am i missing here? Zone or Datatype problem?

**Comment by cgebe** [comment]
Even this is not working...:
```
this.source.setFilter([
    {
        field: 'grade',
        search: '4.0',
        filter: (value: string, search: string) => {
            return parseFloat(value) <= parseFloat(search);
        }
    }
], false);
```

`query` is the input parameter of my applyFilter method

**Comment by shilan** [comment]
i am trying to write a customized filter component, looking at the checkbox, input select filters that smart table already has from here:
https://github.com/akveo/ng2-smart-table/tree/master/src/ng2-smart-table/components/filter/filter-types

`import { Component, NgModule, OnInit } from '@angular/core';
import { FormControl } from '@angular/forms';
import 'rxjs/add/operator/distinctUntilChanged';
import 'rxjs/add/operator/debounceTime';
import 'rxjs/add/operator/skip';
import {DefaultFilter} from 'ng2-smart-table/components/filter/filter-types/default-filter';
;

@Component({
  selector: 'double-input-filter',
  template: `
    <input [(ngModel)]="query"
           [ngClass]="inputClass"
           [formControl]="inputControl"
           class="form-control"
           type="text"
           placeholder="{{ column.title }}" />
    <input [(ngModel)]="query"
           [ngClass]="inputClass"
           [formControl]="inputControl"
           class="form-control"
           type="text"
           placeholder="{{ column.title }}" />
  `,
  styles: []
})
export class DoubleInputFilterComponent extends DefaultFilter implements OnInit {

  inputControl = new FormControl();

  constructor() {
    super();
  }

  ngOnInit() {
    this.inputControl.valueChanges
      .skip(1)
      .distinctUntilChanged()
      .debounceTime(this.delay)
      .subscribe((value: string) => this.setFilter());
  }

}
`
But this doesn't really work. I just don't know how to refer to that in setting property of the table.
Any idea if it is possible?

**Comment by karanhinduja** [comment]
Whats the solution for Custom filter ?
