### ISSUE TITLE
Pagination at top of table

### ISSUE THREAD

**Issue by jiradeto** [akveo/ng2-smart-table#352]
Hi guys ,

I want to display pagination at both position (top and below of table) 
is there any setting for that ? can't find this in document.
if not can I request this feature ?

thank you in advance

**Comment by chiransudha** [comment]
do we have a solution for this?

**Comment by pimmassink** [comment]
Here's a dirty one: 

ng2-smart-table {
display: flex
}

ng2-smart-table-pager {
align-self: end;
margin-top: -60px;
}
