### ISSUE TITLE
More than 10 rows pre table 

### ISSUE THREAD

**Issue by RoryGarner92** [akveo/ng2-smart-table#380]
Anybody Know how to increase the number of rows before the Pagination kicks in ?

**Comment by nkarri** [comment]
add pager in settings
```javascript
settings = {
   pager: {
      display: true,
      perPage: 15
    },
   columns = {
      ...
   }
}
```

**Comment by RoryGarner92** [comment]
It worked, thank you

**Comment by adil-butt** [comment]
> add pager in settings
> 
> ```js
> settings = {
>    pager: {
>       display: true,
>       perPage: 15
>     },
>    columns = {
>       ...
>    }
> }
> ```

Working Perfect
