### ISSUE TITLE
Data from server using RESTFul API

### ISSUE THREAD

**Issue by dgpuranik** [akveo/ng2-smart-table#383]
Hi,

I like the functionality of your ng2-smart-table package. I am trying to use this in my Angular 4 web app. My web app fetch the data from RESTful API. I want attach data I received from API to table. Is it possible? 

Thanks.

**Comment by RoryGarner92** [comment]
I think you need to declare a local data server. and use httpModule. There is an example for this here https://akveo.github.io/ng2-smart-table/#/

**Comment by dgpuranik** [comment]
@RoryGarner92 what do you mean by local data server? There are many tables and links on the suggested page. Will you please send me specific link. I really appreciate your help.

**Comment by RoryGarner92** [comment]
There is the link to the sample.  https://github.com/akveo/ng2-smart-table/blob/master/src/app/pages/examples/server/basic-example-load.component.ts

**Comment by dgpuranik** [comment]
@RoryGarner92 I will implement and get back to you. If its possible then why repo is saying API data source coming soon in read me file. Bit confusing.  
Thanks.

**Comment by Vinutha-BK** [comment]
@dgpuranik 
Hi , Why did you closed this issue. Have u got the solution .Is @RoryGarner92  suggested solution is working for you?

**Comment by AhmedHamedTN** [comment]
I would like to know if this solution worked? else, I'd appreciate some hints

**Comment by dgpuranik** [comment]
@RoryGarner92 's suggested solution works and its pretty simple to implement.

**Comment by meriem-hm** [comment]
@RoryGarner92  i did this but the pagination dosn't work and filtering as well , 
i didn't understand where 's the problem 
 source: ServerDataSource ;
 constructor(http:Http,
  private rowService:RowService)
  
  {   
    var rows =this.rows;
    console.log("/////////this.rows +++++///////////");
  
    this.source=new ServerDataSource (http,{
    endPoint:'http://localhost:3000/api/rows',
    
    pagerLimitKey:"_limit",
    pagerPageKey:"_page",
    sortDirKey: "_order",
    sortFieldKey: "_sort",
    totalKey:'total',
    dataKey:'data',

**Comment by rafalencar1997** [comment]
I had the same issue, the problem is the way it does the request that is probably different from the way your API does it

**Comment by yasmineA** [comment]
@meriem-hm  
If you handle pagination in your backend so you have to specify 
pagerPageKey:'page' 
and 
pagerLimitKey:'page_size' 

like you did with dataKey and others 
page and page_size represent params that your API accept like http://localhost:3000/api/rows/?page=1&page_size=5

the component will put them in your endpoint and replace the value of page_size (here 5) by perPage(20 in the example)  that you specified in settings objects or 10 by default.

example : 
this.sourceServer = new ServerDataSource(this.http, {
        endPoint:  'http://localhost:3000/api/rows',
        totalKey: 'total',
        dataKey: 'data',
        pagerPageKey:'page',
        pagerLimitKey:'page_size'
    });
settings = {
    pager: {
      perPage: 20
    },
    actions:false,
   columns :{
   }
 ...
} 

Hope that will help you

**Comment by hxmwr** [comment]
> this.sourceServer = new ServerDataSource(this.http, {

This works on fetching remote data, but  I can't add new data item still and other server side write options.

**Comment by salehasadi** [comment]
@YasmineA hi, thanks that works for me but i have to send a `Bearer  token` with my request is there anyway to set that!?

**Comment by yasmineA** [comment]
@salehasadi  yes it's possible via an Intercepter that it will add `token` to each http request :

**Comment by yasmineA** [comment]
@salehasadi  yes it's possible via an Intercepter that it will add `token` to each http request : ```import { Injectable, Injector } from "@angular/core";
import {
  HttpRequest,
  HttpHandler,
  HttpEvent,
  HttpInterceptor,
  HttpResponse
} from "@angular/common/http";
import { Router } from "@angular/router";
import { Observable } from "rxjs/Observable";
import { catchError, tap } from "rxjs/operators";

@Injectable()
export class TokenInterceptor implements HttpInterceptor {
  constructor(private injector: Injector) {}
  intercept(
    request: HttpRequest<any>,
    next: HttpHandler
  ): Observable<HttpEvent<any>> {
    var router = this.injector.get(Router);

    request = request.clone({
      setHeaders: {
        Authorization: "JWT " + localStorage.getItem("token")
      }
    });
    return next.handle(request).pipe(
      tap(
        event => {},
        error => {}
      )
    );
  }
}
```

**Comment by haglerw** [comment]
@yasmineA I have challenge accessing the datakey since the data returned from RESTFul API is nested as shown below:

`{
    "response": {
        "status": 200,
        "message": "system users retrieved successfully"
    },
    "data": {
        "content": [
            {
                "id": 1,
                "createdOn": null,
                "softDelete": false,
                "firstName": "",
                "email": "",
                "password": "",
                "lastName": "",
                "phoneNumber": "",
                "roles": [
                    {
                        "id": 1,
                        "createdOn": null,
                        "softDelete": false,
                        "roleName": "",
                        "privileges": [
                            {
                                "id": 4,
                                "createdOn": "",
                                "softDelete": false,
                                "name": ""
                            }
                        ]
                    }
                ]
            }
        ],
        "pageable": {
            "sort": {
                "sorted": false,
                "unsorted": true,
                "empty": true
            },
            "pageSize": 1,
            "pageNumber": 0,
            "offset": 0,
            "unpaged": false,
            "paged": true
        },
        "totalElements": 3,
        "totalPages": 3,
        "last": false,
        "first": true,
        "sort": {
            "sorted": false,
            "unsorted": true,
            "empty": true
        },
        "numberOfElements": 1,
        "size": 1,
        "number": 0,
        "empty": false
    }
}`

Is there a way to get to the datakey with this kind of data?

**Comment by aashishrawte1** [comment]
> Hi,
> 
> I like the functionality of your ng2-smart-table package. I am trying to use this in my Angular 4 web app. My web app fetch the data from RESTful API. I want attach data I received from API to table. Is it possible?
> 
> Thanks.

you can do it by using SeverDataSource like this

this.source = new ServerDataSource(this.http, {
      endPoint: `${environment.backendUrl}/api/***`,
      dataKey: 'data.userList',
      filterFieldKey: 'filterOn',
      sortDirKey: 'desc',
      pagerLimitKey: 'pagerLimit',
      pagerPageKey: 'activePage',
      sortFieldKey: 'sortOn',
      totalKey: 'data.totalUser',
    });

this code is from my project and it is working fine.
this is done by using ng2-smart-table in my project.
