### ISSUE TITLE
Customize the visual of the actions

### ISSUE THREAD

**Issue by HaifaGhidhaoui** [akveo/ng2-smart-table#389]
Hi!
Please I want to customize the visual of the actions! For example, instead "add New", i want to have an icon "+". Is it possible and how?
Thanks in advance.

**Comment by leo420994717** [comment]
in the table setting: 

    add: {
      addButtonContent: '<i class="ion-add"></i>',
      createButtonContent: '<i class="ion-checkmark"></i>',
      cancelButtonContent: '<i class="ion-close"></i>',
      confirmCreate: true
    },

**Comment by HaifaGhidhaoui** [comment]
Thank you very much!
