### ISSUE TITLE
Dropdown list in cell

### ISSUE THREAD

**Issue by stratdaz** [akveo/ng2-smart-table#418]
In edit mode, is it possible to bind a cell to a dropdownlist?

**Comment by Ell3000** [comment]
#10

**Comment by stratdaz** [comment]
Thanks, found that after posting.

**Comment by anushamadadi** [comment]
Is there a change event for the dropdown in edit mode?

**Comment by namrata7618** [comment]
Can anyone help me out to show dropdown list with option in ng2-smart-table and when user click on edit then that value should be selected.
