### ISSUE TITLE
How to access methods inside onComponentInitFunction

### ISSUE THREAD

**Issue by audrys** [akveo/ng2-smart-table#423]
Hi,
I have created table with custom type component. 
columns: {
Plan: {
                title: "Plan",
                type: 'custom',
                renderComponent: IconViewComponent,
                onComponentInitFunction(instance) {
                    instance.click.subscribe(row => {
                        console.debug('row', row, this.someMethod());
                    });
                }
            },
}
I cannot access any method (like this.someMethod()) inside created instance. How to get EventEmitter working on root component
Thanks in advance
Audrius

**Comment by shrop21** [comment]
Hoping for an answer or alternative solution as well!

**Comment by hurcalav** [comment]
I have same problem

**Comment by hadarweiss** [comment]
Same problem here

**Comment by hadarweiss** [comment]
Found the answer - just change the syntax from:
`onComponentInitFunction(instance) {}`
to:
`onComponentInitFunction: (instance: any) => {}`

**Comment by Nayan27raval** [comment]
@hadarweiss  It works for me...Thanks..

**Comment by lvlohammadi** [comment]
@hadarweiss Thanks. it was useful.

**Comment by praveenpds** [comment]
what it really means to me ?? onComponentInitFunction: (instance: any) => {} , please interpret

**Comment by hurcalav** [comment]
@praveenpds 
example:
`
morebtn: {
                title: '',
                filter: false,
                type: 'custom',
                renderComponent: ButtonMoreComponent,
                onComponentInitFunction(instance) {
                    instance.save.subscribe(row => {
                              ......
                    });
                }
            }`

**Comment by praveenpds** [comment]
@hurcalav : thanks  and pls what actually this trick is doing ,kindly brief it  ...

**Comment by zeeshancb** [comment]
still not working,

**Comment by praveenpds** [comment]
Feel free to close this

**Comment by mhnatiuk** [comment]
it doesn't work, "this" is still undefined inside the function. Which is to be expected, since we define this function before any initialization is actually done. But still, I don't know how to refer to component's method other than using "this", which makes this kinda hard to use in a real-life scenario

**Comment by craigchandler** [comment]
This is not resolved for accessing this.function1 where function1 resides in calling component, not the rendercomponent 
example: where clearRow() is in component hosting the table
onComponentInitFunction(instance: any) {
          instance.clear.subscribe(row => {
            this.clearRow(row);
          });

**Comment by renanaribeiro** [comment]
Actually there is an error on docs...
You can call this function this way:

onComponentInitFunction: (instance) => {
    instance.click.subscribe(() => { this.openModal(); });
},

I was facing the same issue and found by [this reply](https://github.com/akveo/ng2-smart-table/issues/718#issuecomment-417271488)
