### ISSUE TITLE
how to post the newData to server?

### ISSUE THREAD

**Issue by ZeyZhang** [akveo/ng2-smart-table#429]
first,i get data from server,when the data was changed,i want post new data to server. And the code like this.please tell me how to do.
```
settings = {
    hideSubHeader: true,
    actions: {
      columnTitle: '操作',
      delete: false
    },
    edit: {
      editButtonContent: '<i class="ion-edit"></i>',
      saveButtonContent: '<i class="ion-checkmark"></i>',
      cancelButtonContent: '<i class="ion-close"></i>',
      confirmSave: true,
    },
    columns: {
      name: {
        title: '趋势值',
        type: 'string'
      },
      type: {
        title: '类型',
        type: 'string'
      },
      fBand: {
        title: '频段',
        type: 'string'
      },
      min: {
        title: '提醒报警阀值',
        type: 'string'
      },
      middle: {
        title: '警告报警阀值',
        type: 'string'
      },
      max: {
        title: '故障报警阀值',
        type: 'string'
      },
      unit: {
        title: '单位',
        type: 'string'
      },
      updateAt: {
        title: '创建时间',
        type: 'string'
      }
    }
  };

  data: LocalDataSource = new LocalDataSource();

  ngOnInit(){
    this.route.params.subscribe((params: Params) => {
      this.sensorId = params['id'];
    })
    this.service.getData(sessionStorage.getItem('userId'), this.sensorId).subscribe(res => {
      for (let i = 0; i < res.length; i++) {
        let times = new Date(res[i].updateAt);
        res[i].updateAt = times.toLocaleString();
      }
      this.data.load(res);
    })
  }

  onUpdate(e) {
    let param = {
      id: null,
      type: 0,
      alarms: []
    };
    param.id = this.sensorId;
    param.alarms = e.source.data;

    this.service.updateSetting(sessionStorage.getItem('userId'), param)
      .subscribe(res => {
        e.confirm.resolve();
      });
  }
```

**Comment by ouchl** [comment]
add to html template:
`(editConfirm)="onEditConfirm($event)"`

add onEditConfirm method to the component class
`onEditConfirm(event): void {
    event.confirm.resolve();
    this.service.saveData(event.newData);
  }`

implement saveData method in your service.

**Comment by ZeyZhang** [comment]
thanks.

**Comment by spilote72** [comment]
Hi, 

There is another option: I created a class derived from LocalDataSource and implemented prepend, update, delete. 

I actually call my backend on completion of the Promise of super().insert().then(...). And if you have a generic interface for doing crud operations, then you need only 1 derrived class to wich you pass a reference to your "repository" interface. Works very nice;y actually! No need to clutter HTML and ts file with event handlers... just new MyCustomDataSource(mydata, myInterfaceToGenericRepository).

import { LocalDataSource } from 'ng2-smart-table';
import { IDataStore } from 'data-store.interface'; // my own interface

//
// Custom Data Source for use in Ng2-data-table. Allows interraction with any IDataStore<T> data store.
//
export class StoreDataSource extends LocalDataSource {
    constructor(data: Array<any>, private dataStore: IDataStore<any>) {
        super(data);
    }

    prepend(element: any): Promise<any> {
        let promise = this.dataStore.insert(element, true).toPromise();

        return promise;
    }
    
    remove(element: any): Promise<any> {
        let promise = this.dataStore.remove(element, true).toPromise();

        return promise;
    }

    update(element: any, values: any): Promise<any> {
        let promise = this.dataStore.update(element, true).toPromise();

        return promise;
    }
}

Cheers
