### ISSUE TITLE
Want editable:true for "Add" but editable:false for "Edit"

### ISSUE THREAD

**Issue by susandy** [akveo/ng2-smart-table#44]
Hi,

Is there any way to keep column editable for "Add New" action but keep editable:false for "edit" row?

**Comment by nnixaa** [comment]
Hi @susandy, yes, take a look at `actions.edit` property here https://akveo.github.io/ng2-smart-table/documentation. Let me know if this helps.

**Comment by susandy** [comment]
Thanks for reply. I used action.edit property to display edit button and editable:true to make column editable.
But my requirement is
**For column A --
 editable property should be true for "add" action so that I can enter value for that column during "add" but this editable property should be false for "edit" action

I am not sure how can I achieve with this property

**Comment by radha89** [comment]
+1

**Comment by moirobin** [comment]
Hi,
Did you find a way to do it ? 
My column has : `editable: false` to prevent change but it's no longer possible to add a new row.
