### ISSUE TITLE
column filter type custom

### ISSUE THREAD

**Issue by Pierozi** [akveo/ng2-smart-table#447]
Hello there,

I'm trying to customize a filter component, the documentation says it's same behavior as editor, but is seems not. This feature is not yet developed ? I can open a PR if it's still on the planning.

```javascript
cinemaWeekStart: {
  title: 'Date From',
  filter: {
    type: 'custom',
    component: DatePickerEditorComponent,
  },
  editor: {
    type: 'custom',
    component: DatePickerEditorComponent,
  },
},
```

Thanks.

**Comment by corahchiu** [comment]
I have the same issue.

**Comment by tonioros** [comment]
I have the same issue too,  the property component of filter, call component, but don't render html ( I want render a MyDateRangePicker component).

I saw a commentary in a issue, and said: "Make a component look like to base FilterComponent"
(https://github.com/akveo/ng2-smart-table/blob/master/src/ng2-smart-table/components/filter/filter.component.ts), but not work.

**Comment by jorgearal** [comment]
I have the same problem, i'm trying to edit the code but with not too much success
