### ISSUE TITLE
Disable any particular ROW

### ISSUE THREAD

**Issue by maheshp212** [akveo/ng2-smart-table#463]
Hello,

I want to disable some rows in my table based on some conditions in the data, is there any possible way to do it. like disabling the total row and not giving the actions option.

Thanks in advance

**Comment by NordRagnarok** [comment]
I'm looking for a way to style a particular row depending on a condition in the data..
if anyone knows about a way to do this?

**Comment by maheshp212** [comment]
Thanks for the prompt answer.. it helped me..
