### ISSUE TITLE
Cannot apply styling

### ISSUE THREAD

**Issue by janpansa** [akveo/ng2-smart-table#464]
I have tried all the solutions in this issues list and none have been successfull. I am trying to remove all the "**blue**" links on the table and change them to **red**.

I have tried :

1 - Styling via SCSS via node modules
2 - Using component styling on the component itself.
3 - Using app css and scss.
4 - using deep and host selectors. (/deep/ is depricated and does not work anymore.)
5 - removing styles by setting the "defaultStyle: false," property in typescript.

Nothing worked for me. I can provide code if needed. Please help ?

**Comment by janpansa** [comment]
I managed to get this working by adding the following component styling :

@Component({
  selector: 'app-product-retailers',
  templateUrl: '../../html/products/product-retailers.component.html',
  styles: [`

      :host /deep/ ng2-smart-table tbody > tr > td:first-child { 
              color: #ED1C24;
      }

      :host /deep/ ng2-smart-table tbody > tr > td > a { 
              color: #ED1C24;
      }

      :host /deep/ ng2-smart-table tbody > tr > th > a { 
              color: #ED1C24;
      }

      :host /deep/ a { color: #ED1C24; }
      :host /deep/ a:link { color: #ED1C24; }
      :host /deep/ a:hover { color: #ED1C24; }
      :host /deep/ a:focus { color: #ED1C24; }

      :host /deep/ ng2-smart-table a { color: #ED1C24; }
      :host /deep/ ng2-smart-table a:link { color: #ED1C24; }
      :host /deep/ ng2-smart-table a:hover { color: #ED1C24; }
      :host /deep/ ng2-smart-table a:focus { color: #ED1C24; }

      :host /deep/ tr.ng2-smart-row a { color: #ED1C24; }
      :host /deep/ tr.ng2-smart-row a:link { color: #ED1C24; }
      :host /deep/ tr.ng2-smart-row a:hover { color: #ED1C24; }
      :host /deep/ tr.ng2-smart-row a:focus { color: #ED1C24; }

  `]
})

**Comment by janpansa** [comment]
Hi managed to get this working by adding the following component styling :

@Component({
  selector: 'app-product-retailers',
  templateUrl: '../../html/products/product-retailers.component.html',
  styles: [`

      :host /deep/ ng2-smart-table tbody > tr > td:first-child { 
              color: #ED1C24;
      }

      :host /deep/ ng2-smart-table tbody > tr > td > a { 
              color: #ED1C24;
      }

      :host /deep/ ng2-smart-table tbody > tr > th > a { 
              color: #ED1C24;
      }

      :host /deep/ a { color: #ED1C24; }
      :host /deep/ a:link { color: #ED1C24; }
      :host /deep/ a:hover { color: #ED1C24; }
      :host /deep/ a:focus { color: #ED1C24; }

      :host /deep/ ng2-smart-table a { color: #ED1C24; }
      :host /deep/ ng2-smart-table a:link { color: #ED1C24; }
      :host /deep/ ng2-smart-table a:hover { color: #ED1C24; }
      :host /deep/ ng2-smart-table a:focus { color: #ED1C24; }

      :host /deep/ tr.ng2-smart-row a { color: #ED1C24; }
      :host /deep/ tr.ng2-smart-row a:link { color: #ED1C24; }
      :host /deep/ tr.ng2-smart-row a:hover { color: #ED1C24; }
      :host /deep/ tr.ng2-smart-row a:focus { color: #ED1C24; }

  `]
})

**Comment by janpansa** [comment]
Hi managed to get this working by adding the following component styling :

@component({
selector: 'app-product-retailers',
templateUrl: './app.component.html',
styles: [`

  :host /deep/ ng2-smart-table tbody > tr > td:first-child { 
          color: #ED1C24;
  }

  :host /deep/ ng2-smart-table tbody > tr > td > a { 
          color: #ED1C24;
  }

  :host /deep/ ng2-smart-table tbody > tr > th > a { 
          color: #ED1C24;
  }

  :host /deep/ a { color: #ED1C24; }
  :host /deep/ a:link { color: #ED1C24; }
  :host /deep/ a:hover { color: #ED1C24; }
  :host /deep/ a:focus { color: #ED1C24; }

  :host /deep/ ng2-smart-table a { color: #ED1C24; }
  :host /deep/ ng2-smart-table a:link { color: #ED1C24; }
  :host /deep/ ng2-smart-table a:hover { color: #ED1C24; }
  :host /deep/ ng2-smart-table a:focus { color: #ED1C24; }

  :host /deep/ tr.ng2-smart-row a { color: #ED1C24; }
  :host /deep/ tr.ng2-smart-row a:link { color: #ED1C24; }
  :host /deep/ tr.ng2-smart-row a:hover { color: #ED1C24; }
  :host /deep/ tr.ng2-smart-row a:focus { color: #ED1C24; }
`]
})

**Comment by mmanavaz** [comment]
I'm trying to change the style of the cancel button from reading "Cancel" to an x like the x's on Font Awesome. Can this be done?

**Comment by yalexhwang** [comment]
@Anky001 where should i add the css code? I added it to my .scss file as usual but it's not reflected. Adding 'attr' to the setting object works though.

`:host /deep/ ng2-smart-table  {
  	font-size:16px
  }`

**Comment by josephjoju2** [comment]
this worked for me in angular:
 **add this following code to styles.css** 

 ng2-smart-table table tr th a {
  color: red !important;
  }
