### ISSUE TITLE
How to add table settings dynamically?

### ISSUE THREAD

**Issue by apgiridharan** [akveo/ng2-smart-table#483]
settings is not updated dynamically.

For column editor type 'list'. I want to load the list from the server. 

How can i do this?

**Comment by lopenchi** [comment]
You can request the list and when you have a response, you can do:

 this.settings['columns'] = this.tables[this.selectedTableId].columns;

In this case I'm filling the columns info with info from server.
So, you can create your object columns and fill in settings.


In HTML :
 <ng2-smart-table [settings]="settings" [source]="tableData">
    </ng2-smart-table>

**Comment by NordRagnarok** [comment]
@lopenchi 
Can you please give more info on what you're doing?
I'm trying to acheive this as well - I want to populate a column list options (or auto-complete options) via a remote server (HTTP requests), but can't get the table to "rerender" the options once it's already on the HTML...
I have a row, in that row there are 4 columns with lists, the options on each list is dependent on the value of the list before it..  but once the table is rendered into the template I can't get the list options to show 'show' values when a droplist value is changed...

**Comment by lopenchi** [comment]
@NordRagnarok 
I really dont know how to do your requirement.
I think you should open another issue explaining the re-rendering problem.

**Comment by alexsc123** [comment]
Hi,
In order to change the setting dynamically you need to use **Object.assign**.
For example:
HTML:
`<ng2-smart-table [settings]="settings" [source]="tableData"> </ng2-smart-table>`
//before change settings:
 `settings = {
        columns: {}     
    }`

//new settings:
 `newSettings = {
        columns: { 
first_column: {
                title: 'first_column',
                type: 'number'
            }
        }    
    }`

// assign the new settings
`settings = Object.assign({}, newSettings );`

Hope it helps,
Alex.

**Comment by FiReBlUe45** [comment]
Is it possible to add an inline mode and external combined?

**Comment by NordRagnarok** [comment]
ngOnChanges is triggered ONLY when you assign a complete object to the whole 'settings' variable, on partial assign it will not be triggered...

**Comment by apgiridharan** [comment]
Thank you all.

**Comment by Romsan01** [comment]
Wrap the "smart table" in ngIf and wait for the data to load :)

**Comment by GazousGit** [comment]
Hi Romsan, could you elaborate about this ngIf tag for the smart-table rendereing refresh.
I tried all the above solutions but nothing render even if the settings have changed.

**Comment by solomon911** [comment]
> In order to change the setting dynamically you need to use **Object.assign**.

When i add settings dynamically, the table reloads, and since i'm using server side rendering, multiple api calls are triggered. Any idea how i can suppress the event that triggers it?

**Comment by rbrijesh** [comment]
> Hi,
> In order to change the setting dynamically you need to use **Object.assign**.
> For example:
> HTML:
> `<ng2-smart-table [settings]="settings" [source]="tableData"> </ng2-smart-table>`
> //before change settings:
> `settings = { columns: {} }`
> 
> //new settings:
> `newSettings = { columns: { first_column: { title: 'first_column', type: 'number' } } }`
> 
> // assign the new settings
> `settings = Object.assign({}, newSettings );`

You saved my time, Thank you.

**Comment by AlexsonSP** [comment]
> { columns: {} }

TANKS!!!

**Comment by AlexsonSP** [comment]
> Hi Romsan, could you elaborate about this ngIf tag for the smart-table rerender.
> I tried all the above solutions but nothing render even if the settings have changed.
> What should I put in the ngif tag to refresh the table ?
> 
> Edit: The objectAssign is working and the table rerender if, for example I want to add a new column, however it doesn't do anything if I change the perPage var.
> 
> this.source.setPaging(1, number, true);
> 
> (**1** is the page, (it doesn't really matter which page); **number** is my var for perPage; **true** for showing the pager)



TANKS

**Comment by darshana2496** [comment]
> setPaging

it is very helpful if you share any code snippet for reference

Thank you in advance

**Comment by luisGithubPeru** [comment]
If this helps someone, when I want to reload my settings dynamically I use *ngIf with ChangeDetectorRef from @angular/core to rebuild the object, here's an example:

component.html:
`<ng2-smart-table *ngIf="showTables" [settings]="fileTableSettings" [source]="fileTableSource">  `

component.ts
```
import { ChangeDetectorRef, OnChanges, SimpleChanges } from '@angular/core';

  fileTableSettings ={
      actions: {add:true, edit:false, delete: false}
      (... other settings...)
  }
  constructor(private changeDetector: ChangeDetectorRef) {}

  ngOnChanges(changes: SimpleChanges): void {
    if (changes.someElementChanged) {
      this.fileTableSettings.actions = { add: false, edit: true, delete: false };
      this.refreshTables();
    }
  }

  private refreshTables(){
    this.showTables = false;
    this.changeDetector.detectChanges();
    this.showTables = true;
  }
````

**Comment by maximLyakhov** [comment]
On maintained [dj-fiorex fork](https://github.com/dj-fiorex/angular2-smart-table) did it with default CD strategy and:
```
  this.settings = { ...config };
  this.source = this.facade.data.pipe(
    tap((data) => this.table.prepareSource().load(data))
  );
  this.cdr.detectChanges();
```

We somehow need to reload data after changing settings object and call CDR implicitly.
