### ISSUE TITLE
ReadOnly Table

### ISSUE THREAD

**Issue by federhico** [akveo/ng2-smart-table#485]
Can the table be ReadOnly ? 
i need to hide the add, edit and delete buttons, only filter and sorting should be avaiable.

**Comment by tcc-world** [comment]
why did you close this? Kindly answer this.

**Comment by gokcer** [comment]
Same question. I want to make table only readonly. How can I disable action buttons?

**Comment by gokcer** [comment]
@federhico I tried to configure table like this and it worked. Maybe it helps.


 <ng2-smart-table [settings]="settings" [source]="...">
        </ng2-smart-table>

settings = {
    actions: {
      columnTitle: '',
      add: false,
      edit: false,
      delete: false,
      custom: [],
      position: 'left',
    },
    columns: {
      ...
    },
  };
