### ISSUE TITLE
the example basic-example-button-view.component doesn't work

### ISSUE THREAD

**Issue by FiReBlUe45** [akveo/ng2-smart-table#488]
Hello,
I tried to make this example work:
https://github.com/akveo/ng2-smart-table/blob/master/src/app/pages/examples/custom-edit-view/basic-example-button-view.component.ts

But the function is not called, no console.log etc
```
renderComponent: ButtonViewComponent,
        onComponentInitFunction(instance) {
          console.log('call')
          instance.save.subscribe(row => {
            alert(`${row.name} saved!`)
          });
        }
```

**Comment by dario30186** [comment]
how did you solve this issue?

**Comment by FiReBlUe45** [comment]
@dario30186 I just think I upgraded ng2-smart-table
