### ISSUE TITLE
The built-in checkbox column filter stopped working after upgrading to v1.2.0

### ISSUE THREAD

**Issue by hadarweiss** [akveo/ng2-smart-table#489]
I used the built-in checkbox column filter as described in the example here: [advanced filters example](https://github.com/akveo/ng2-smart-table/blob/master/src/app/pages/examples/filter/advanced-example-filters.component.ts)

With v1.0.3 everything worked well but when I upgraded to v1.2.0 the checkbox filter stopped working.

**Comment by NordRagnarok** [comment]
What is your code?
I'm using 1.2.1 and checkbox filter works well..

**Comment by hadarweiss** [comment]
Code example:
`
columns: {
isActive: {
        title: 'Active',
        type: 'custom',
        renderComponent: BooleanCellComponent,
        filter: {
          type: 'checkbox',
          config: {
            true: true,
            false: false,
            resetText: 'clear',
          },
        }
      }
}`

I used the checkbox filter a couple of times for boolean values.

**Comment by NordRagnarok** [comment]
Try this:
filter: {type: 'checkbox', config: {true: 'true', false: 'false'}}

**Comment by NordRagnarok** [comment]
Also in PR #427 I've inserted support for checkbox render type, so you could use it instead of 
type: custom with renderComponent

**Comment by hadarweiss** [comment]
@NordRagnarok Thanks, it's working 👍
