### ISSUE TITLE
EditConfirm event data = newData

### ISSUE THREAD

**Issue by nORKy54** [akveo/ng2-smart-table#50]
When I use de the editConfirm event, the data object has the new value, not the old.
With this bug, difficult to find what is changed

**Comment by hkb1990** [comment]
I got the same issue above. After looking into the code, I find that the function [getNewData()](https://github.com/akveo/ng2-smart-table/blob/master/src/ng2-smart-table/lib/data-set/row.ts#L28) has some problems. `Object.assign` will change the value of `this.data`.

Maybe code should be like following:
```js
getNewData(): any {
  let values =  Object.assign({}, this.data);
  this.getCells().forEach((cell) => values[cell.getColumn().id] = cell.newValue);
  return values;
}
```

**Comment by nnixaa** [comment]
Thanks @hkb1990, just merged it.
