### ISSUE TITLE
How to get double click on the row

### ISSUE THREAD

**Issue by saadfaisal** [akveo/ng2-smart-table#513]
I am using ng2-smart-table on an ngModal and i would like to close the modal when a user double clicks on any row. How do i get the double click event on a row ?

**Comment by saadfaisal** [comment]
This is how i was able to accomplish it

```
 lastClickTime: number = 0;

  onRowSelect(event) {
    if (this.lastClickTime === 0) {
      this.lastClickTime = new Date().getTime();
    } else {
      const change = (new Date().getTime()) - this.lastClickTime;
      if (change < 400) {
       this.onDoubleClick();
      }
      this.lastClickTime = 0;
    }
  }
```

**Comment by SantaUA** [comment]
@saadfaisal still any way to do it by this library so i used your way of implementation, thanks

**Comment by PietroLaGrotta** [comment]
1) Implement the following static class:

export class MouseGuard{
    static lastClickTime:number = 0;

    static isDoubleClick():boolean{

        var dc:boolean = false;

        if (MouseGuard.lastClickTime === 0){
            MouseGuard.lastClickTime = new Date().getTime();
        }
        else{
            dc = ( ((new Date().getTime()) - MouseGuard.lastClickTime) < 400);
            MouseGuard.lastClickTime = 0; 
        }

        return dc;
    }
}


2) in your page.component.ts that use ng2-smart-table implement the following method:

onUserRowSelected(event): void {
    if (MouseGuard.isDoubleClick()){
      this.onEdit(event); // for example... 
    }
  }

**Comment by AbdulhadiLab** [comment]
as @PietroLaGrotta says
> 1. Implement the following static class:
> 
> ```
> export class MouseGuard{
>     static lastClickTime:number = 0;
> 
>     static isDoubleClick():boolean{
> 
>         var dc:boolean = false;
> 
>         if (MouseGuard.lastClickTime === 0){
>             MouseGuard.lastClickTime = new Date().getTime();
>         }
>         else{
>             dc = ( ((new Date().getTime()) - MouseGuard.lastClickTime) < 400);
>             MouseGuard.lastClickTime = 0; 
>         }
> 
>         return dc;
>     }
> }
> ```
> 
> 1. in your page.component.ts that use ng2-smart-table implement the following method:
> 
> ```
> onUserRowSelected(event): void {
>     if (MouseGuard.isDoubleClick()){
>       this.onEdit(event); // for example... 
>     }
>   }
> ```
I implement the same way but you should add 
``` 
            if(dc){
              MouseGuard.lastClickTime = 0; 
            }else{
              MouseGuard.lastClickTime = now;
            } ```
in case you get the first click and after 500 millisecond you start a double click you should take the second and third click together as a double click

**Comment by Peeripapo** [comment]
If you want to be able to distinguish between single click and double click you can use this:

lastClick: number = 0;

  onRowSelect(event) {
    this.lastClick += 1;
    setTimeout(() => {
      if (this.lastClick > 1) {
        this.onDoubleClick(event);
      } else {
        if (this.lastClick > 0) {
          this.onSingleClick(event);
        }
      }
      this.lastClick = 0;
    }, 500);
}
