### ISSUE TITLE
Internet Explorer Support

### ISSUE THREAD

**Issue by GaZaTu** [akveo/ng2-smart-table#514]
ng2-smart-table doesn't work in Internet Explorer 11.
It doesn't get displayed.
Please help me fix this problem.
Thanks in advance

**Comment by harikrishnan-u01** [comment]
Even the https://akveo.github.io/ng2-smart-table/#/ page doesn't load in IE 11.

**Comment by kohanevich85** [comment]
I've solved the issue by adding these dependencies (package.json)

dependencies:   
   "array.from": "^1.0.3",
    "babel-polyfill": "^6.23.0",
    "babel-runtime": "^6.23.0",

devDependencies:
  "babel-plugin-transform-runtime": "^6.23.0",

**Comment by brgaulin** [comment]
Appears to be still missing some polyfills, getting:
```
Unable to get property 'apply' of undefined or null reference
```

on the demo page

**Comment by kirtanleela** [comment]
dependencies:
"array.from": "^1.0.3",
"babel-polyfill": "^6.23.0",
"babel-runtime": "^6.23.0",

devDependencies:
"babel-plugin-transform-runtime": "^6.23.0",

Still issue remains same. 
"Unable to get property 'apply' of undefined or null reference "

Here is my package.json
{
  "name": "decima",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --proxy-config proxy.config.json --port 4200",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "stop": "sudo kill `sudo lsof -t -i:4200`",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@agm/core": "1.0.0-beta.0",
    "@angular/animations": "^4.3.0",
    "@angular/common": "4.3.0",
    "@angular/compiler": "4.3.0",
    "@angular/core": "4.3.0",
    "@angular/forms": "4.3.0",
    "@angular/http": "4.3.0",
    "@angular/platform-browser": "4.3.0",
    "@angular/platform-browser-dynamic": "4.3.0",
    "@angular/router": "4.3.0",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-beta.6",
    "@ngx-translate/core": "^7.0.0",
    "@ngx-translate/http-loader": "0.1.0",
    "@swimlane/ngx-charts": "6.0.0",
    "@swimlane/ngx-datatable": "9.3.1",
    "angular-4-data-table": "^0.4.6",
    "angular-4-data-table-bootstrap-4": "^0.2.0",
    "angular-calendar": "0.19.0",
    "angular-tree-component": "3.8.0",
    "angular2-json-schema-form": "^0.7.0-alpha.1",
    "angular2-multiselect-dropdown": "^2.7.0",
    "angular2-text-mask": "8.0.2",
    "array.from": "^1.0.3",
    "babel-polyfill": "^6.23.0",
    "babel-runtime": "^6.23.0",
    "bootstrap": "^4.0.0-alpha.6",
    "classlist.js": "^1.1.20150312",
    "core-js": "2.4.1",
    "d3": "^4.8.0",
    "dragula": "3.7.2",
    "intl": "^1.2.5",
    "jsoneditor": "^5.14.1",
    "ng-multiselect-dropdown": "^0.1.3",
    "ng-sidebar": "6.0.1",
    "ng2-dragula": "1.5.0",
    "ng2-file-upload": "1.2.1",
    "ng2-smart-table": "^1.2.2",
    "ng2-validation": "4.2.0",
    "ngx-toastr": "6.4.1-beta.0",
    "ngx-ui-switch": "^1.6.0",
    "quill": "1.2.6",
    "resize-observer-polyfill": "^1.4.2",
    "rxjs": "^5.4.2",
    "screenfull": "3.3.1",
    "spinthatshit": "1.0.3",
    "text-mask-addons": "3.6.0",
    "web-animations-js": "^2.2.5",
    "zone.js": "0.8.13"
  },
  "devDependencies": {
    "@angular/cli": "1.2.1",
    "@angular/compiler-cli": "4.3.0",
    "@angular/language-service": "4.3.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3",
    "babel-plugin-transform-runtime": "^6.23.0"
  }
}
