### ISSUE TITLE
how to use pipes? 

### ISSUE THREAD

**Issue by mmdsharifi** [akveo/ng2-smart-table#52]
Hi,
I want to change form of dates. for example:

`2016-10-09T07:00:41.387Z` to `2016/10/09`, in angular 2 we can use 'shortDate' pipe parameter, but  how  do it in ng2-smart table

**Comment by AlexTheBest** [comment]
Hey mmdsharifi, i ran into this a few weeks ago and the way i solved it is using the valuePrepareFunction property.

For example to format the date:
```
      valuePrepareFunction: (date) => { 
        var raw = new Date(date);

        var formatted = this.datePipe.transform(raw, 'dd MMM yyyy');
        return formatted; 
      }
```

Make sure you export the datePipe and define it in the constructor

`import { DatePipe } from '@angular/common';`

`constructor( private datePipe: DatePipe ){  }`

**Comment by nnixaa** [comment]
As for now this is the only possible way. Closing as resolved, let us know if there any other questions.

**Comment by ohabash** [comment]
@AlexTheBest does `valuePrepareFunction` go in the setting object?

**Comment by ohabash** [comment]
Oh i see... I got stuck at 2 places.

1. valuePrepareFunction needs to go in the column key object like this

```
	settings = {
	  columns: {
	    buildQty: {
	      title: 'buildQty'
	    },
	    created: {
	      title: 'created',
		  valuePrepareFunction: (created) => {
		    return this.datePipe.transform(new Date(created), 'dd MMM yyyy');
		  }
	    },
	    username: {
	      title: 'User Name'
	    },
	    email: {
	      title: 'Email'
	    }
	  },
	};
```

2. using the date pipe in a component (NG 6+) also needs to be defined as a provider in that component . Like this 

```
@Component({
  selector: 'xxx',
  templateUrl: './xxx.component.html',
  styleUrls: ['./xxx.component.scss'],
  providers: [DatePipe]
})
```

**Comment by bessam-haj-salem** [comment]
i try to use pipe but inside my pipe there's async data : 
my pipe : 
```
import { Pipe, PipeTransform } from "@angular/core";
import { VehiculeService } from "app/pages/fleetManagement/services/vehicule.service";

@Pipe({
  name: "convertVehicule"
})
export class ConvertVehiculePipe implements PipeTransform {
  constructor(private vehicleService: VehiculeService) {}

  transform(value) {
    this.vehicleService.getVehicules().subscribe(
      (data: any = []) => {
        for (let j = 0; j < data.length; j++) {
          if (value === data[j].id) {
            return data[j].registration_number;
          }
        }
      },
      error => {
        console.log(error);
      }
    );

    return value;
  }
}
```
```
 valuePrepareFunction: cell => {
            let newValue = this.convertVehiclePipe.transform(cell);
            return newValue;
          }
```
I did this but no value is rendered, i thinked to use async like {{  data | async }} because the data is asynchronus , but where
