### ISSUE TITLE
Add Custom Button in table header(thead)

### ISSUE THREAD

**Issue by ronit123321** [akveo/ng2-smart-table#522]
Can we add a custom button in the table header which on click perform some event? 
This is what I had in mind
![capture](https://user-images.githubusercontent.com/23359872/30053247-c1df683a-9245-11e7-8dc9-89cad059f0dc.JPG)

Even if I add an empty column in the settings the title would accept a string and the HTML is printed as it is on screen.

**Comment by NordRagnarok** [comment]
You can just add a 'menu' button above the table, and clicking it will do some action (with the data from the table or different data)

**Comment by ronit123321** [comment]
@NordRagnarok I am able to add a button above the table thead and perform column toggle perfectly, but I would like to know if there is any method by which I could add HTML to the thead section. 
My team thinks that visually that will be the perfect place to align the toggle button. 
The docs are only helpful to a limit.

**Comment by NordRagnarok** [comment]
@ronit123321 
Currently in the code there isn't a method (or settings) that will insert a multi purpose 'menu' button at the thead section
