### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by DZcoderX** [akveo/ng2-smart-table#534]
Hi, I'm not sure if I am installing this correctly? I do have angular 4 installed on to my computer but when I follow the installation guide, I get this:
![image](https://user-images.githubusercontent.com/16616714/30455030-5a89e63c-996c-11e7-9080-5f919a1c94f8.png)

**Comment by FARHANE** [comment]
I think it's OK its just warnings I have that all the times :D

**Comment by DZcoderX** [comment]
What are your commands on installing? I can't seem to get it running with just: "npm install --save ng2-smart-table" and then doing "ng serve --port <5000>"
Which directory do I go to do "ng serve ..."? Is it after the folder called: 'smarttable'? If so, it doesn't work for me :(

**Comment by FARHANE** [comment]
you must be under the project folder and execute : npm install --save ng2-smart-table
you will see that a folder with the name ng2-smart-table is created in you node_modules.
after that go to your module and add : 
```
import { Ng2SmartTableModule } from 'ng2-smart-table';
// ...

@NgModule({
  imports: [
    // ...
    
    Ng2SmartTableModule,
    
    // ...
  ],
  declarations: [ ... ]
})
// ...
```
now can use the component.

**Comment by DZcoderX** [comment]
Thanks @FARHANE 
Where do I add the ' import { Ng2SmartTableModule } from ....'?
What's the file called?

**Comment by FARHANE** [comment]
In your module for example AppModule, or any module that you created.
Supposing that you want to show the list of users, maybe you have a UserModule,
you will have User folder:
User
|--------> user-component : folder
     |--------> user.component.ts
     |--------> user.component.spec.ts
|--------> user-list-component : folder
     |--------> user-list-component.ts
....
|--------> user.module.ts ------> **here**

**Comment by FARHANE** [comment]
Sorry but your questions in not about the component but about the logic of angular.
please go to the angular documentation.

**Comment by DZcoderX** [comment]
Thanks I figured it all out now
