### ISSUE TITLE
Checkbox Implementation

### ISSUE THREAD

**Issue by saketk6** [akveo/ng2-smart-table#535]
Hello,
I have tried everything in documentation but the checkbox didn't displayed on this table.
Is it not possible to use them in this table, If NOT can anyone help me out with this??

**Comment by FARHANE** [comment]
```
settings = {
    selectMode: 'multi',
    actions: {
      delete: false,
      add: false,
      edit: false,
      select: true,
    },
....
}
```

**Comment by saketk6** [comment]
thanks it worked, but it's not giving any <table heading > for select button, it's directly giving a checkbox for selecting all on the top, i want a heading over their, IS IT POSSIBLE???

**Comment by FARHANE** [comment]
Sorry I don't understand what are you saying.
The component is not working perfectly with multiselect, for example, you can not set selected rows by default, or you will lose selection after clicking on the next page...

**Comment by saketk6** [comment]
no it's workin fine... but as you can see, i want something written at the select all checkbox on top such as "select All".

![xxx](https://user-images.githubusercontent.com/30998016/30482999-d485e748-9a42-11e7-9c58-fc0e224e96ed.jpeg)

**Comment by FARHANE** [comment]
Ok, but I don't think it's possible.

**Comment by harshkan** [comment]
how to get selected fileds

**Comment by MADJIYoucef** [comment]
@FARHANE /*Sorry I don't understand what are you saying.
The component is not working perfectly with multiselect, for example, you can not set selected rows by default, or you will lose selection after clicking on the next page... */
For this problem have you an issue??

**Comment by FARHANE** [comment]
@MADJIYoucef 
I developped my own solution based on Angular Material

**Comment by sliemansalah** [comment]
@FARHANE 
Share us the solution for it, I have same problem

**Comment by ongkristopher** [comment]
> @FARHANE
> Share us the solution for it, I have same problem

https://stackoverflow.com/a/53418561 this might help you!

**Comment by namrata7618** [comment]
![chckbox](https://user-images.githubusercontent.com/49127188/84902300-496d3e80-b0ca-11ea-9d13-683fab469a4c.PNG)
1. After adding checkbox for multi selection, when i do Add new then column get distorted, any help would be helpful.
2. Select box not showing selectText as i have already defined

**Comment by KanagarajUI** [comment]
namrata7618 let me know if you find solution . .am trying to fix this one

**Comment by namrata7618** [comment]
@KanagarajUI
No i did not get any solution for above two mentioned points,  please update me once it gets fix.

**Comment by sujitha454** [comment]
Hi, nedd some help,In my case I want the select mode is need to get at right side like as shown in attached image can you  please suggest me thanks in advance
![Screenshot_15](https://user-images.githubusercontent.com/62258250/100413636-e67ecb00-309d-11eb-9ffa-e37ae27d25d3.png)
