### ISSUE TITLE
custom actions is not working

### ISSUE THREAD

**Issue by KhaledElAnsari** [akveo/ng2-smart-table#565]
I'm trying to add a custom action, I followed [this example](https://github.com/akveo/ng2-smart-table/blob/master/src/app/pages/examples/custom-edit-view/basic-example-custom-actions.component.ts#L13) but it's not working! and I didn't even find this option in the documentation so is this a valid example or it's deprecated ?

**Comment by mfsi-surajs** [comment]
Did you find solution? If so please share.
Thank you.

**Comment by jarredszabadi** [comment]
did you put (custom)="onCustom($event)" in your html?

**Comment by mfsi-surajs** [comment]
yes, I did.
Do I have to put icon anywhere? I've strong feeling that I should define icon, but can't find where?

**Comment by jarredszabadi** [comment]
i did something like this.

`actions: {
          edit: false,
          delete: false,
          add: false,
          custom: [
            {
              name: 'view',
              title: '<i class="ion-information-circled ng2-smart-actions"></i>',
            },
          ],
        },`

**Comment by mfsi-surajs** [comment]
I did the same but not working for me,
`actions: {
      add: true,
      edit: true,
      delete: true,
      custom:[
        {
          name: 'Copy',
          title: '<i class="ion-ios-plus-outline ng2-smart-actions"></i>'
        },
      ]
    },`

**Comment by jarredszabadi** [comment]
make sure you are using v1.2.2. otherwise sorry can't help.

**Comment by mfsi-surajs** [comment]
mindfire@mindfire-Vostro-2520:~/Projects/rfs_web$ sudo npm ng2-smart-table -version
[sudo] password for mindfire:
5.3.0

**Comment by jarredszabadi** [comment]
that's not correct. the highest version for this project is 1.2.2. The custom actions options were released with 1.2.2.

**Comment by mfsi-surajs** [comment]
Thanks,
I'm using smart table of ng2-admin, that could be the problem ?

**Comment by gravypower** [comment]
looks like ng2-admin is using ng2-smart-table: 1.1.0

I was able to install the latest version using the [npm shrinkwrap command](https://nodejs.org/en/blog/npm/managing-node-js-dependencies-with-shrinkwrap/).

These are the commands that I ran from  the project root:
```
npm install
npm shrinkwrap
npm update ng2-smart-table
npm shrinkwrap
```

Hope that helps someone.
