### ISSUE TITLE
Issue sorting with data loaded from server

### ISSUE THREAD

**Issue by emritcey** [akveo/ng2-smart-table#571]
We are having an issue with the built in sort functionality. Data is being loaded from a server data source and appearing correctly in the grid but is not being sorting on click of the table header. The event fires, and you can see it change the arrow indicator but does not change the array.  Also, looking through the data being loaded and comparing it with one from LocalDataSource it appears that TitleComponent >> Source >> filteredAndSorted is empty.

**Comment by nameisvick** [comment]
can you share your code ?
