### ISSUE TITLE
Show image in cells

### ISSUE THREAD

**Issue by mmdsharifi** [akveo/ng2-smart-table#58]
Hi,
I want to show image inside a cell, How it can be possible ?

**Comment by nnixaa** [comment]
Hey @mmdsharifi, a couple of steps to achieve this:
1. set your column (where you want to show an image) type to `type: 'html'`;
2. then use valuePrepareFunction on this column to preprocess the data inserted into a cell:
```
valuePrepareFunction: (value) => { return `<img scr="value" />` }
```

That's it, let me know if you have any other questions.

**Comment by andreirk** [comment]
Hi,
is chekckbox type of colomn now supported? 
In docs I see comlom.type settings that can be html and editor.type  that can be checkbox
but when  I set for a colomn:
        enabled: {
          title: 'Enabled',
          filter: false,
          type: 'html',
          valuePrepareFunction: (value) => { return `<input type="checkbox" name="enabled" value="value" >` },
          editor: {
            type: 'checkbox'
          }
        },

it shows just nothing in that colomn, no content.
And when I click edit, it shows my boolean value as if an input type="text"

Am I missing something?

**Comment by gauravme27** [comment]
@nnixaa i tried your code given above but was unable to access the image.just a logo of image is coming over there.

**Comment by arun-awnics** [comment]
@nnixaa Hi, I have been using ng2 smart table in my project to display the customer's details. I am unable to insert image in the cells. I have tried the above method but couldn't get it working. Is there any work around?

**Comment by arun-awnics** [comment]
Hey @nnixaa I am trying to add buttons and images in the table. I tried the method you have mentioned above. I was unable to display images in the table. Link for my plunkr is: https://plnkr.co/edit/lGP4XsO64gjgnTg9Qpvn?p=preview . Kindly help me fix the issue.

**Comment by arun-awnics** [comment]
I got it done. We have to create renderComponents for each element we insert into the table cells. 
Here is the plunkr for the same: https://plnkr.co/edit/lGP4XsO64gjgnTg9Qpvn?p=preview

**Comment by omkarchavan5595** [comment]
they show me this error (property) valuePrepareFunction: (img: any) => {
    return: string;

valuePrepareFunction: (image) => { return `<img scr="image" />` }

**Comment by MerkulovDev** [comment]
can i return modal window with value of this cell?

**Comment by JairoMarques** [comment]
valuePrepareFunction: (image) => { return <img **src**="image" /> }
==> src 
not 
==> scr

**Comment by Kaveriph** [comment]
Hi, 
Looks like your approach should be working.
But the valuepreparefunction is unable to parse the url of the picture.
I get the 404 (NOT FOUND) error. Could you please have a look?

 http://localhost:4200/$%7Bpicture%7D 404 (Not Found):

This is my column - 
status: {
      title: 'Status',
      type: 'html',
      valuePrepareFunction: (picture:string) => {
        console.log(picture);
        return '<img width="50px" src="${picture}" />';
      },
      filter: false,
    },

the string is printed as expected but the image is not found.
please suggest!

**Comment by buddhikaprasad** [comment]
Hi,

Your approach working fine. But I need to display an image which is getting from an api end point, which returns a base64 string. 

I tried to call the service endpoint from the valuePrepareFunction and it doesn't show the images in the cell.


```
ItemImageId: {
        title: 'Image',
        type:'html',
        valuePrepareFunction: (value) => { 
          this.getItemImage(value).then(
            async a=>{
              console.log(a) ;
              return a ;
            }) },
        width: '5rem',
        filter: false
      },
```
```
getItemImage(imageId)
  {
    var image  =  this.itemService.getItemIconImage(imageId).subscribe(data=> {
      return `<img src=${data.image}  onerror="this.src='./assets/img/default-img-300x180.gif'  class="rounded-circle UserProfileimg" width="40" /><br>`;
    });
  }
```

Can you please add any suggestions ? @nnixaa

**Comment by rbrijesh** [comment]
> picture: {
> title: 'Picture',
> type: 'html',
> valuePrepareFunction: (picture:string) => { return ``<img width="50px" src="${picture}" />``; },
> },
> 
> This works for me, I hope it's useful.



> picture: {
> title: 'Picture',
> type: 'html',
> valuePrepareFunction: (picture:string) => { return ``<img width="50px" src="${picture}" />``; },
> },
> 
> This works for me, I hope it's useful.

Thanks it's working bro @oskcolorado

**Comment by JaquesGF** [comment]
> Hi,
> 
> Your approach working fine. But I need to display an image which is getting from an api end point, which returns a base64 string.
> 
> I tried to call the service endpoint from the valuePrepareFunction and it doesn't show the images in the cell.
> 
> ```
> ItemImageId: {
>         title: 'Image',
>         type:'html',
>         valuePrepareFunction: (value) => { 
>           this.getItemImage(value).then(
>             async a=>{
>               console.log(a) ;
>               return a ;
>             }) },
>         width: '5rem',
>         filter: false
>       },
> ```
> 
> ```
> getItemImage(imageId)
>   {
>     var image  =  this.itemService.getItemIconImage(imageId).subscribe(data=> {
>       return `<img src=${data.image}  onerror="this.src='./assets/img/default-img-300x180.gif'  class="rounded-circle UserProfileimg" width="40" /><br>`;
>     });
>   }
> ```
> 
> Can you please add any suggestions ? @nnixaa

You may have already solved the problem, but I managed to upload the photo like this:

        valuePrepareFunction: (picture) => {
          picture= `data:image/jpeg;base64,${picture}`;
          return  this.sanitizer.bypassSecurityTrustHtml(`<img src="${picture}" height="50" width="50"/>`);
        }

I need to use

        private sanitizer: DomSanitize in constructor

But I still need to deal with the error scenario when receiving the photo

**Comment by CollegeStars** [comment]
poster: {
        title: 'Round Poster',
        type: 'html',
        valuePrepareFunction: (poster) => { return `<img src="${poster}"  width="100px"/>` }
      },

**Comment by zeinebKH** [comment]
hi 
i want to add link in cell in this link there is video but the video dosen't work
`type: {
        title: 'Type',
        valuePrepareFunction: (type) => {
          if(type==="A"){
            return  'Action';
          } else {
            return  'Error';
          }
        } 
      },
      videoName: {
        title: 'video',
        type: 'custom',
        renderComponent: LinkVideoComponent,
        onComponentInitFunction(instance) {
          instance.save.subscribe(row => {
            alert(`${row.videoName} !!!!`)
          });
        }
      },`
LinkVideoComponent:
`export class LinkVideoComponent implements OnInit,ViewCell {

  renderValue: string;

  @Input() value: string | number;
  @Input() rowData: any;

  @Output() save: EventEmitter<any> = new EventEmitter();
  @ViewChild('videoPlayer') videoplayer: ElementRef;

  @ViewChild("content") modalContent: TemplateRef<any>;


  constructor(private modalService: NgbModal) {}

  ngOnInit() {
    this.returnLinkVideo();
  }
  returnLinkVideo() {
    this.renderValue = '' + this.value + '';
  }

  onClick() {
    this.save.emit(this.rowData);
    this.modalService.open(this.value, { size: 'lg'});
    this.videoplayer.nativeElement.play();
  
  }`
in Html
`<p #videoplayer (click)="onClick()" >{{ renderValue }}</p>`
the video in o folder in the same folder project i didn't know how to get it, any help
