### ISSUE TITLE
how apply css form-control in completer-dropdown-holder and using editor.config.completer?

### ISSUE THREAD

**Issue by vinhWater** [akveo/ng2-smart-table#586]
Hi Team,
I would like thank so much to team, this project *(include ng2-admin, ngxxxx)* help me touch angular 2 easily. 
I stucks in customize ng2-smart-table with completer *(my project bases on ng2-admin, I love this theme)*. I'm try to work around to add style css **form-control** behind **completer-input** and luckily it works *(2 places: completer-cmp.js, completer-cmp.ts)*, but **completer-holder** not work.
In addition, any example how using editor.config.completer in ng2-smart-table , I tried finding and working around myself but unluckily.
Here my code:
Add form-control behind completer-input
![Add form-control behind completer-input](https://image.ibb.co/dybL36/Screen_Shot_2017_10_28_at_12_04_52_AM.png)

Setting completer of ng2-smart-table
![Setting completer of ng2-smart-table](https://image.ibb.co/kYTBAm/Screen_Shot_2017_10_28_at_12_08_00_AM.png)

completer-holder not apply css form-control of ng2-admin
![completer-holder not apply css form-control of ng2-admin](https://image.ibb.co/mSFV36/Screen_Shot_2017_10_28_at_12_09_40_AM.png)
Thanks for watching my issue.

**Comment by vinhWater** [comment]
working around with ng2-completer from [https://www.npmjs.com/package/ng2-completer](npmjs.com) and luckily it works expected.

**Comment by liuhao2050** [comment]
Same question here，So, What is the solution for this？

**Comment by huybn5776** [comment]
```
addCssToNg2Completer() {
  setTimeout(() => {
    let ng2CompleterCollection = document.getElementsByTagName("ng2-completer");
    for (let i = 0; i < ng2CompleterCollection.length; i++) {
      let ng2Completer = ng2CompleterCollection[i];
      let inputElement = ng2Completer.children[0].children[0];
      inputElement.classList.add("form-control");
    }
  });
}
```
It's work, but maybe there is another better way to do is.
