### ISSUE TITLE
Remove Placeholder from Filter?

### ISSUE THREAD

**Issue by sridharkrishnan** [akveo/ng2-smart-table#599]
Hi,I want to remove the placeholder from Filter Search bar.
Thanks in Advance

**Comment by dtpniel** [comment]
I have the same issue too. Anyone knows how to remove the placeholders?

**Comment by sridharkrishnan** [comment]
Hi @dtpniel  remove the Placeholder from the file filter.component.ts
Here is the exact Path:<Your System path>\node_modules\ng2-smart-table\src\ng2-smart-table\components\filter.component.ts
And the template look like
<div class="ng2-smart-filter" *ngIf="column.isFilterable">
      <input 
        [(ngModel)]="query"
        (keyup)="_filter($event)"
        [ngClass]="inputClass"
        class="form-control"
        type="text" 
        />
    </div>
  `
