### ISSUE TITLE
Support to Angular 5

### ISSUE THREAD

**Issue by calebeaires** [akveo/ng2-smart-table#601]
Angular has been updated to version 5, angular-cli has follow this update. Does ng2-smart-table will be update soon?

**Comment by Moushumi2701** [comment]
I am using angular 5.and getting the @avkeo/ng2-completer error while doing ng serve in my application. I did all the above steps. But then got the below error:

ERROR in node_modules/@akveo/ng2-completer/src/components/completer-cmp.d.ts(54,9): error TS1086: An accessor cannot be declared in an ambient context

**Comment by Sebi11** [comment]
Did you try to force an installation of ng2-completer in version 3.0.3 for example? If I remember correctly, adding this dependency in my package.json fixed the problem. The dependency is [this one](https://www.npmjs.com/package/ng2-completer), I'm not sure modifying the node_modules folder was a good idea...
