### ISSUE TITLE
Custom renderComponent EventEmitter Subscribe Cannot access properties and functions

### ISSUE THREAD

**Issue by andredatsch** [akveo/ng2-smart-table#626]
I have a grid with a custom renderComponente, it's a button that change some properties on the object, it's working, but with a small issue:

When i change the data, it do not refresh the source, and when i try to force the reload, it looks like the listener doesen't have access to the properties and functions

Here is the column declaration:
![grid](https://user-images.githubusercontent.com/3539904/33281841-c43a7604-d38d-11e7-91da-7fec572358b7.png)
when i try to force the source to load the provider, the following error happens:

![log](https://user-images.githubusercontent.com/3539904/33281853-cf0c2fdc-d38d-11e7-9768-38a5a957ce4a.png)

i've tryed to call some of my component functions, to access properties, but nothing work, and after googling sometime, i didn't find an answer, anyone know how to fix that problem?

**Comment by dizco** [comment]
This looks related to your closure on the `clickGrid.subscribe`. Your error message states that `this` is undefined. Have a look at how JavaScript closures work and that might solve your issue

**Comment by andredatsch** [comment]
I was following the example from this [link](https://github.com/akveo/ng2-smart-table/blob/master/src/app/pages/examples/custom-edit-view/basic-example-button-view.component.ts), And it really works, but can't access nothing besides the event.

i will check the closure and post the feedback soon as possible

**Comment by andredatsch** [comment]
OK, that fixed the problem 
![grid fixed](https://user-images.githubusercontent.com/3539904/33388056-037dcb70-d516-11e7-8998-ff7d334696ae.png)

**Comment by cleodegario** [comment]
@andredatsch it still not working for me but there is no error on console, can you tell me what version of angular and ng2-smart-table are you using?

My Button Component:
`import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { ViewCell } from 'ng2-smart-table/ng2-smart-table';

@Component({
    template: `
    <button (click)="onClick()" class="btn green btn-flat">{{renderValue}}</button>
    `
})
export class ButtonRenderComponent implements ViewCell {

    renderValue: string;
    @Input() value: string | number;

    @Input() rowData: any;

    @Output() save: EventEmitter<any> = new EventEmitter();

    ngOnInit() {
        this.renderValue = this.value.toString().toUpperCase();
    }

    onClick(): void {
        console.log('deu certo');
        this.save.emit(this.rowData);
    }
}`

`button: {
        title: 'Button',
        type: 'custom',
        renderComponent: ButtonRenderComponent,
        onComponentInitFunction: (instance: any) => {
          instance.save.subscribe(row => {
            alert('test');
          });
        }
      }`

**Comment by andredatsch** [comment]
@cleodegario i'm using version 1.2.2

**Comment by ignivasandeepkumar** [comment]
+1

**Comment by dvirHam** [comment]
+1

**Comment by miguelleitevieira** [comment]
I use the onComponentInitFunction in button, but I need to subscrive data for another component. Someone know how to bind this?
