### ISSUE TITLE
Custom Filtering

### ISSUE THREAD

**Issue by jorgearal** [akveo/ng2-smart-table#632]
I'm looking for adding a custom filter to my table. I have some dates to filter and I'm looking for a usable way to filter them. I have tried with editing the following file, adding this to the template and an Input:
https://github.com/akveo/ng2-smart-table/blob/master/src/ng2-smart-table/components/filter/filter.component.ts

`<div *ngSwitchDefault
                    [innerHTML]="customComponent">
      </div>`

`@Input() customComponent: Filter ;`

In addition to this, my custom filter component extends of Filter, but it doesn't work

Overmore, I couldn't make the Input works, not even as string

How can I achieve a custom filtering based on components?

**Comment by sravank84** [comment]
I have the same issue, I am trying to use a Datepicker or a DateRangePicker for a date column filter. Can someone please help ? Any help is much appreciated.

**Comment by alexandr-efimov** [comment]
Any updates, guys?
