### ISSUE TITLE
How to prepare data when editing ?

### ISSUE THREAD

**Issue by chellem** [akveo/ng2-smart-table#638]
Hello,

I've been able to use the `valuePrepareFunction` to properly display an object in the grid.  However I can't find a function to do the same when edit the value. When I edit the value am getting `[object Object]` in the field which is normal since it's not getting the right value from a property.

Can any one sort me out with this issue?

**Comment by Chetan36** [comment]
Hello,

I am having the exact same problem. Every time I use the `valuePrepareFunction` to display the `object.value` in grid, it disappears when I am trying to edit the value. Even if I try to update it nonetheless, it does not even update that value.

Please look into this issue.

Thanks in advance.

**Comment by ganapathymano** [comment]
Hi @chellem, @Chetan36 I am also having the same issue, can you please give me a solution to solve the issue

**Comment by carnevlu** [comment]
Any update about this issue ?
apart from that it has been closed...

**Comment by hope4555** [comment]
Same here , when editing i see the underlying value
