### ISSUE TITLE
ng2-smart-table data how to use a pipe?

### ISSUE THREAD

**Issue by syoubaku** [akveo/ng2-smart-table#67]
if I hava a `date` in my data like this.
![image](https://cloud.githubusercontent.com/assets/12625278/19850075/7c050358-9f91-11e6-90ac-ed058baa9068.png)
what I should do to translate the date to yyyy-MM-dd HH:mm:ss ?

**Comment by syoubaku** [comment]
https://github.com/akveo/ng2-smart-table/issues/52

**Comment by zhanghongyublog** [comment]
> #52

any answer else ?

**Comment by zhanghongyublog** [comment]
> if I hava a `date` in my data like this.
> ![image](https://cloud.githubusercontent.com/assets/12625278/19850075/7c050358-9f91-11e6-90ac-ed058baa9068.png)
> what I should do to translate the date to yyyy-MM-dd HH:mm:ss ?

any answer else ?

**Comment by akshayhandoo** [comment]
@xiaomoinfo i have achieved this by the following way:
columns: {
            id: {
                title: Id,
                type: 'number',
                sort: false
            },
            Date: {
                title: Date,
                type: 'date',
                valuePrepareFunction: (date) => {
                    if (date) {
                        return new DatePipe('he-IL' or 'en-GB' ['any lang code you want]).transform(date, 'dd/MM/yyyy hh:mm');
                    }
                    return null;
                },
                sort: false
}

**Comment by bessam-haj-salem** [comment]
i try to use pipe but inside my pipe there's async data : 
my pipe : 
```
import { Pipe, PipeTransform } from "@angular/core";
import { VehiculeService } from "app/pages/fleetManagement/services/vehicule.service";

@Pipe({
  name: "convertVehicule"
})
export class ConvertVehiculePipe implements PipeTransform {
  constructor(private vehicleService: VehiculeService) {}

  transform(value) {
    this.vehicleService.getVehicules().subscribe(
      (data: any = []) => {
        for (let j = 0; j < data.length; j++) {
          if (value === data[j].id) {
            return data[j].registration_number;
          }
        }
      },
      error => {
        console.log(error);
      }
    );

    return value;
  }
}
```

And this is my function :
```

 valuePrepareFunction: cell => {
            let newValue = this.convertVehiclePipe.transform(cell);
            return newValue;
          }
```
I did this but no value is rendered, i thinked to use async like {{  data | async }} because the data is asynchronus , but where
