### ISSUE TITLE
Is it possible to have a row selected and sorted by default? 

### ISSUE THREAD

**Issue by areknow** [akveo/ng2-smart-table#710]
I would like the table to load, and have a predetermined row already selected for sorting.

**Comment by miki995** [comment]
Me too... :dancer:

**Comment by augustoicaro** [comment]
Use "SortDirection" like this:

```
settings = {
    actions: false,
    columns: {
      columnKey: {
        title: 'title', sortDirection: 'desc'
      }
    }
  };
```

[documentation](https://akveo.github.io/ng2-smart-table/#/documentation)

_Originally posted by @agupadilla in https://github.com/akveo/ng2-smart-table/issues/974#issuecomment-472992466_

This can solve your problem to sort rows.
