### ISSUE TITLE
Get Row selected from anywhere click on Row in select mode multi

### ISSUE THREAD

**Issue by ayushshuklash** [akveo/ng2-smart-table#721]
in the multi-select mode the userRowSelect event only when clicked on the checkbox , is there a way to make it occur when clicked anywhere on the row

**Comment by mohammad0omar** [comment]
i know that this is a very late answer,  but maybe you can use "rowClassFunction" and add an event emitter for each row

**Comment by ayushshuklash** [comment]
Thank you @mohammad0omar for your reply, Yes I did the same and created many other features too.

**Comment by mohammad0omar** [comment]
Please feel free to share those features to the community.
