### ISSUE TITLE
Delay keyDown filter type

### ISSUE THREAD

**Issue by hosseinGanjyar** [akveo/ng2-smart-table#748]
I get data from server and ng2-smart-table filters is very fast in typing search. I want after 1 second of keyDown in filterbox, table send filters query to server.
How do this?

**Comment by meriem-hm** [comment]
i 'm not able to filtering data from ng2-smart-table 
i'm using server as well , so if you want can you tell me what should i do to filtering data

**Comment by meriem-hm** [comment]
`` source: LocalDataSource = new LocalDataSource();
 
 //source :ServerDataSource ;
   constructor(http:Http,
  
   private ligneService:LigneService,
   private service: GenieTablesService,)
 
 {
   this.source = new ServerDataSource(http, {
  endPoint: 'http://localhost:3000/api/lignes',
  pagerLimitKey: "_limit",
  pagerPageKey: "_page",
  sortDirKey: "_order",
  sortFieldKey: "_sort",
 //dataKey: 'data',
  totalKey: 'x_total_count'
});




}

**Comment by hosseinGanjyar** [comment]
please mail to me your code.
hossein.ganjyar@gmail.com

**Comment by ElliotAlexander** [comment]
Was there ever a solution to this?

**Comment by hosseinGanjyar** [comment]
I have migrated to [ngx-datatable](https://github.com/swimlane/ngx-datatable). This is best solution for table in angular framework.
