### ISSUE TITLE
filtering issue

### ISSUE THREAD

**Issue by meriem-hm** [akveo/ng2-smart-table#764]
I get data from server but i'm not able to filter data ,
this is a part of my code 
source: LocalDataSource = new LocalDataSource();
 
 //source :ServerDataSource ;
 constructor(http:Http,
   private ligneService:LigneService,
   private service: GenieTablesService,)
 
 {
   this.source = new ServerDataSource(http, {
  endPoint: 'http://localhost:3000/api/lignes',
  pagerLimitKey: "_limit",
  pagerPageKey: "_page",
  sortDirKey: "_order",
  sortFieldKey: "_sort",
 dataKey: 'data',
  totalKey: 'x_total_count'
});

}

**Comment by mmuttharasan** [comment]
I am also facing same problem.Are you got any solution for the issue?.Pagination doesn't work and filtering as well

**Comment by guilhermefinotti** [comment]
I am also facing same problem. Are you got any solution for the issue?
