### ISSUE TITLE
After upgrading to Angular 6 cant build with AOT

### ISSUE THREAD

**Issue by ovesyan19** [akveo/ng2-smart-table#808]
ERROR in : Unexpected value 'Ng2SmartTableModule in /node_modules/ng2-smart-table/ng2-smart-table.module.d.ts' imported by the module 'AppModule in app.module.ts'. Please add a @NgModule annotation.

**Comment by vsiddharthv** [comment]
Same issue here : 

ERROR in : Unexpected value 'Ng2SmartTableModule in ~/node_modules/ng2-smart-table/ng2-smart-table.module.d.ts' imported by the module 'AppModule in ~/src/app/app.module.ts'. Please add a @NgModule annotation.

**Comment by Syperia** [comment]
This pull request fixes this issue: https://github.com/akveo/ng2-smart-table/pull/801. Currently merged. We're all waiting for release.

**Comment by nnixaa** [comment]
Duplicate of #798
