### ISSUE TITLE
Issue in IE 10/11 - Syntax error

### ISSUE THREAD

**Issue by ovesyan19** [akveo/ng2-smart-table#818]
![capture](https://user-images.githubusercontent.com/5383351/41537131-31f5ea58-7310-11e8-9998-f25c9708b8eb.PNG)

**Comment by rharirrk** [comment]
I got same issue like that .... please give me the solution as soon

![issue1](https://user-images.githubusercontent.com/40573279/41860065-4ceb7e62-78bb-11e8-8769-7b2ea899ce2b.png)
![issue2](https://user-images.githubusercontent.com/40573279/41860067-4d28c25e-78bb-11e8-8ebd-72b13c45ddff.png)

**Comment by ovesyan19** [comment]
@rharirrk yeah, and it brokes all application so it can't start

**Comment by ovesyan19** [comment]
Please let me know when you expect to work on this issue

**Comment by rharirrk** [comment]
thanks for reply, it was so urgent give me the solution by two days, I
already worked few  project with this plugin this is so good
please give me as soon . thanks again

**Comment by nnixaa** [comment]
Hey Guys, could you let us know a version of tables you have?

**Comment by ovesyan19** [comment]
@nnixaa Hi, I’m using 1.3.3, latest one along with angular 6.0.7 , also the latest one

**Comment by rharirrk** [comment]
@nnixaa I'm also using latest version of ng2-smart and angular

**Comment by darkdog79** [comment]
i use nt2-smart-table 1.3.3 and angular 5.2.0 but does'nt  work on IE 11, error File : vendor.bundle.js, line : 1256, column : 1

something about an IE 11 problem?

**Comment by nnixaa** [comment]
@ovesyan19 @rharirrk @darkdog79, I just published 1.3.5 version, could you try it and let me know if it's working now?

**Comment by ovesyan19** [comment]
@nnixaa yeah ,it's working, thx a lot!
