### ISSUE TITLE
Please update dependencies to angular 6 !

### ISSUE THREAD

**Issue by dilotec-2015** [akveo/ng2-smart-table#819]
get a lot of errors in angular 6:

ERROR in ./node_modules/ng2-completer/directives/ctr-input.js
Module not found: Error: Can't resolve 'rxjs/Observable' in 'C:\xampp\htdocs\select-test\node_modules\ng2-completer\directives'
ERROR in ./node_modules/ng2-completer/directives/ctr-list.js
Module not found: Error: Can't resolve 'rxjs/Observable' in 'C:\xampp\htdocs\select-test\node_modules\ng2-completer\directives'
ERROR in ./node_modules/ng2-completer/services/local-data.js
Module not found: Error: Can't resolve 'rxjs/Observable' in 'C:\xampp\htdocs\select-test\node_modules\ng2-completer\services'
ERROR in ./node_modules/ng2-completer/services/completer-base-data.js
Module not found: Error: Can't resolve 'rxjs/Subject' in 'C:\xampp\htdocs\select-test\node_modules\ng2-completer\services'
ERROR in ./node_modules/ng2-completer/directives/ctr-list.js
Module not found: Error: Can't resolve 'rxjs/add/observable/timer' in 'C:\xampp\htdocs\select-test\node_modules\ng2-completer\directives'
ERROR in ./node_modules/ng2-completer/components/completer-cmp.js
Module not found: Error: Can't resolve 'rxjs/add/operator/catch' in 'C:\xampp\htdocs\select-test\node_modules\ng2-completer\components'
ERROR in ./node_modules/ng2-completer/services/remote-data.js
Module not found: Error: Can't resolve 'rxjs/add/operator/catch' in 'C:\xampp\htdocs\select-test\node_modules\ng2-completer\services'
ERROR in ./node_modules/ng2-completer/services/local-data.js
Module not found: Error: Can't resolve 'rxjs/add/operator/catch' in 'C:\xampp\htdocs\select-test\node_modules\ng2-completer\services'
ERROR in ./node_modules/ng2-completer/directives/ctr-list.js
Module not found: Error: Can't resolve 'rxjs/add/operator/do' in 'C:\xampp\htdocs\select-test\node_modules\ng2-completer\directives'
ERROR in ./node_modules/ng2-completer/services/remote-data.js
Module not found: Error: Can't resolve 'rxjs/add/operator/map' in 'C:\xampp\htdocs\select-test\node_modules\ng2-completer\services'
ERROR in ./node_modules/ng2-completer/directives/ctr-list.js
Module not found: Error: Can't resolve 'rxjs/add/operator/retryWhen' in 'C:\xampp\htdocs\select-test\node_modules\ng2-completer\directives'

**Comment by vsiddharthv** [comment]
Just checked. The package.json and package-lock.json is referring to v1.6.3 of ng2-completer. I think that is what is causing this issue.

**Comment by yhercouet** [comment]
Any update on this? The latest version cannot be used with Angular 6 unless those dependencies are updated

**Comment by tcc-world** [comment]
any update on this? 
How to solve this?

**Comment by Ivan0xFF** [comment]
You actually need ng2-completer 3.0.0-beta.1 to get ng2-smart-table running under Angular 6

**Comment by Ivan0xFF** [comment]
There's actually a simple solution to get ng2-smart-table working on Angular 6. Install rxjs-compat package.

That took a lot of digging to figure out...

**Comment by yhercouet** [comment]
Installing rxjs-compat might be a temporary solution but not the right one just to fix this problem.

I don't understand that the latest version is supposed to work with Angular 6 since the dependencies are not updated to work with Angular 6.

**Comment by vsiddharthv** [comment]
@Ivan0xFF Thank you!! You saved my day (a couple of weeks actually)!!!

@yhercouet Yeah. I hope the repo gets update as soon as possible. But I think rxjs-compat will solve the problem for critically blocked projects.

**Comment by nnixaa** [comment]
Hey Guys, can someone consolidate this as a PR? I would merge/release it asap.

**Comment by yhercouet** [comment]
I don't have the time right now but I'll look into it later if I can.

**Comment by vsiddharthv** [comment]
@nnixaa Please review my changes and publish them on #824

**Comment by nnixaa** [comment]
1.3.4 is released now. ng2-completer has been moved to peerDependencies, so now it is required to install the desired version directly to your project. Hope it resolves the issue!

**Comment by Riyash-D** [comment]
My issue has been fixed by changing ng2-completer version  to 2.0.8 from 1.6.3.

**Comment by Tutankhazulu** [comment]
My issue was also fixed by upgrading to 2.0.8
