### ISSUE TITLE
How to  show [object object]

### ISSUE THREAD

**Issue by kaleu50** [akveo/ng2-smart-table#822]
I have a table purchase and the server returns me purchase with client and the data of that client as I do to show name and id of that client
![image](https://user-images.githubusercontent.com/6022688/41812942-b0069014-7702-11e8-8fab-ee005af7f83d.png)

**Comment by pellyadolfo** [comment]
Put a console.log(myObject) to see the structure of your object and understand the properties that i contains and after try myObject['property'] to show specific properties. Probably you can also use myObject.property.

**Comment by kaleu50** [comment]
Hi, I'm sorry but my problem was a Json in another json as client.buy.name
I got it with the following function` valuePrepareFunction (client) => {return buy.name}`
