### ISSUE TITLE
adding dropdown action list instead of action edit and delete option

### ISSUE THREAD

**Issue by rahuldev761** [akveo/ng2-smart-table#83]
I want to know in this smart table there is any option to create own custom action/dropdown list  or insert html content like button, checkbox.

**Comment by Tibing** [comment]
Hi @rahuldev761!
Yes, of course you can. Please, use
```
"columnKey": {
  type: 'html'
}
```
property to column in which you want insert html, then cell value will be inserted like html. Probably you should use [Angular DomSanitizer](https://angular.io/docs/ts/latest/api/platform-browser/index/DomSanitizer-class.html), to make it work correctly.

**Comment by guillaumegtr** [comment]
Hi,
I'm trying to create a dropdown list in every cell of a colomn using the 'html' type like you said.
It just shows the values, one next to each other without creating a dropdown list. I am probably doing something wrong, is it possible to get an example or to tell me why it is not working ?

![image](https://user-images.githubusercontent.com/36165858/36431874-ba09eaee-1626-11e8-84b0-21863c1f7247.png)
![image](https://user-images.githubusercontent.com/36165858/36432036-2ac1b5d2-1627-11e8-98d6-051eb63776be.png)


Thank you.
