### ISSUE TITLE
Filter gets applied only after second character

### ISSUE THREAD

**Issue by minextu** [akveo/ng2-smart-table#842]
While upgrading from 1.2.2 to 1.3.5, I noticed that the filter does only get applied after the second character is inserted. 
This was not the case with 1.2.2 and is a bit annoying when trying to filter single digit numbers.

Can also be reproduced in the example (https://akveo.github.io/ng2-smart-table)

**Comment by Ivan0xFF** [comment]
I'm also experiencing this issue. Were you able to come up with a solution or workaround?

**Comment by minextu** [comment]
No, I didn't investigated further and just downgraded to 1.2.2 for now

**Comment by AnubrataDS** [comment]
Any updates on this ? I'm facing the same issue when copy-pasting values into the search box
