### ISSUE TITLE
Remove _like from json filter - how to?

### ISSUE THREAD

**Issue by nutysy** [akveo/ng2-smart-table#848]
Hi, how can I remove from filter json: 
?fileName_like=test&_page=1&_limit=10
this '_like', to have result like this:
?fileName=test&_page=1&_limit=10
Is it any configuration feature?
Jarek.

**Comment by AbleLincoln** [comment]
You need to pass in config parameters to your Data Source constructor. You can view all the config options [here](https://github.com/akveo/ng2-smart-table/blob/master/src/ng2-smart-table/lib/data-source/server/server-source.conf.ts). For your case, you want to edit the `filterFieldKey` like so:
``` javascript
new ServerDataSource(data, {
   filterFieldKey: '#field#'
}
```

**Comment by nutysy** [comment]
Thank you!

**Comment by mPishtra** [comment]
How do i format the filter string like a a json table?
For example if I filter based on a column:
[{"filteredField": "nameOf the field", "value":"whateverTyped"}]

**Comment by JeansReal** [comment]
its possible to override the field?

Like to convert to camel case?

`?file_name=test`

**Comment by AbleLincoln** [comment]
@JeansReal I believe the name of the field comes from your `settings`. So in your case your `settings` object will need to look something like
```js
{
   columns: {
      file_name: {
        // ... file_name column settings here
      },
     // ... more column settings here
    },
  }
```

Of course, this will send a GET request to your Server Source like so: `?file_name_like=test`. If you want to remove that `_like` just follow my [instructions above](https://github.com/akveo/ng2-smart-table/issues/848#issuecomment-408993120)

Hope this helps!

**Comment by HuguesGauthier** [comment]
Is it possible to get full example of passing config parameters to Data Source constructor ?

**Comment by AbleLincoln** [comment]
It depends on which config options you require, but you can see a minimal version in my [response here](https://github.com/akveo/ng2-smart-table/issues/848#issuecomment-408993120).
