### ISSUE TITLE
How to remove the placeholder from the ng2-smart-table filter?

### ISSUE THREAD

**Issue by EvgenyProkopovich** [akveo/ng2-smart-table#852]
![image](https://user-images.githubusercontent.com/39822739/43458182-dde8c10e-94d1-11e8-8691-db9fdd8a41cd.png)
How to remove the placeholder from the ng2-smart-table filter?

**Comment by ltmed** [comment]
```
columns: {
      id: {
        title: 'ID',
        filter: false
      } 
}
```
you need to set filter false for each columns, If you need to remove all

**Comment by pjambo** [comment]
> ![image](https://user-images.githubusercontent.com/39822739/43458182-dde8c10e-94d1-11e8-8691-db9fdd8a41cd.png)
> How to remove the placeholder from the ng2-smart-table filter?

**In your css you can try this:**
`:host /deep/ ng2-smart-table thead
  > tr.ng2-smart-filters
  > th.ng2-smart-th
  > ng2-smart-table-filter
  > div.ng2-smart-filter
  > default-table-filter
  > input-filter
  > input::placeholder {
        color: transparent !important;
     }`

**Comment by EvgenyProkopovich** [comment]
@pjambo  thank!

**Comment by rikarikun** [comment]
settings = {
    hideSubHeader: true,
    ...
    }
