### ISSUE TITLE
Pagination starts at page=0

### ISSUE THREAD

**Issue by AbleLincoln** [akveo/ng2-smart-table#858]
Currently when the ServerDataSource retrieves the first page of data, it GETs the page indexed at 1, like so: `<API endpoint>?_page=1`.

Is it possible to have pagination start at the zeroth page?

**Comment by anshumansworld** [comment]
@AbleLincoln did you find the solution?

**Comment by AbleLincoln** [comment]
No sorry, not yet. I had sort of forgotten about this issue and moved on to other things. Let me look back into it. The solution might just be to extend the class and change what we need. Stay posted

**Comment by AbleLincoln** [comment]
Here's the quickest (but kind of silly) fix I found:
Change line `112` of [server.data-source.ts](https://github.com/akveo/ng2-smart-table/blob/master/src/ng2-smart-table/lib/data-source/server/server.data-source.ts) to this:
```ts
```

**Comment by AbdullahUsmani** [comment]
I created a new class: **CustomServerDataSource**, extending the **ServerDataSource** class. 
```javascript
export class CustomServerDataSource extends ServerDataSource 
```

In this class, I overrode the method **addPagerRequestParams** : 
```javascript
addPagerRequestParams(httpParams: HttpParams): HttpParams {
     if (this.pagingConf && this.pagingConf['page'] && this.pagingConf['perPage']) {
        httpParams = httpParams.set(this.conf.pagerPageKey, this.pagingConf['page'] + (-1));
        httpParams = httpParams.set(this.conf.pagerLimitKey, this.pagingConf['perPage']);
    }
    return httpParams;
}
```

The method has only one line different from the original class, done as suggested by @AbleLincoln here:


> Here's the quickest (but kind of silly) fix I found:
> 
> Change line `112` of [server.data-source.ts](https://github.com/akveo/ng2-smart-table/blob/master/src/ng2-smart-table/lib/data-source/server/server.data-source.ts) to this:
> 
> ```ts
> httpParams = httpParams.set(this.conf.pagerPageKey, this.pagingConf['page'] + (-1));
> ```
> 
> What I did was add the `+ (-1)` to the `this.pagingConf['page']`. This changes the value of the HTTP parameter for the 'page' parameter. Essentially anytime an HTTP request is made for data (so when the table is first created, or the user changes to a new page), you just subtract 1 from the page number. This basically gives you zero-indexed paging.
> 
> > Sidenote: the reason you have to do `+ (-1)` instead of `-1` is some Javascript nonsense. `httpParams.set()` expects a string for the second argument. I guess in Javascript you can add a number to a string and it all works out and can be safely converted to a string. But if you want to _subtract_ a number then the compiler gets fussy and refuses to convert that into a string. IDK man Javascript is wack
> 
> Now, this isn't a very robust or smart fix. And we're essentially just hacking the code. What I think needs to be done is that data source should have a config option for where you want your indexing to start. However, this requires changing quite a bit of the code (there are a bunch of hardcoded `1`'s throughout the codebase 😬), so I present this temporary, simpler solution for now. It might be worth submitting a pull request later on down the line
