### ISSUE TITLE
Table do not update after load data

### ISSUE THREAD

**Issue by csepmdat** [akveo/ng2-smart-table#9]
Hi all,

I have a problem when try to load data from API to the table, the table do not update unless I click on the filter box and click out.

Template
`<ng2-smart-table [settings]="settings" [source]="pages"></ng2-smart-table>`

Typescript
```
export class PageListComponent {
    pages: LocalDataSource;

    settings = {
        columns: {
            id: {
                title: 'ID'
            },
            title: {
                title: 'Title'
            },
            edit_link: {
                title: 'Action'
            }
        },
        pager: {
            display: true,
            perPage: 10
        }
    };

    constructor(private pageSerice:PageService) {
        this.pages = new LocalDataSource();
        
        pageSerice.getAllPage().toPromise().then(data => {
            this.pages.load(data);
            this.pages.reset();
        });
    }
}
```
Service
```
getAllPage() {
        //noinspection TypeScriptUnresolvedFunction
        return this.http.get(window.location.origin + "/api/page").map(res => res.json());
}
```

Please help me solve this problem. Thank you so much.

**Comment by nnixaa** [comment]
Hey @csepmdat, could you let me know the module version, please? Also, you don't need the 'reset' call as 'load' resets the table itself.

**Comment by csepmdat** [comment]
@nnixaa 
I am using ng2-smart-table 0.1.6 and Angular2 RC5

**Comment by nnixaa** [comment]
@csepmdat I see, thanks for the vide! Looks like an issue with rc5, let me check this.

**Comment by nnixaa** [comment]
@csepmdat just tried on rc5 and could not reproduce the issue, would you mind creating a plunkr or sharing a complete code you use?

**Comment by csepmdat** [comment]
@nnixaa Hello, I just figured out that this issue is caused by another directive. Sorry for this and slow response.
I'll close this.

**Comment by nnixaa** [comment]
@csepmdat no problem, glad it worked out well.

**Comment by Moreirax** [comment]
@ivivivn Hey, i got the same problem, how did you manage to resolve it?

**Comment by tonioros** [comment]
i have the same problem, how did you resolve it? i set pager pagination perPage property, and not refresh the number pagination.

**Comment by nhdanh** [comment]
How to resolve it ? My table only load when I click any where in my form. My data get from my API

**Comment by ivivivn** [comment]
@Moreirax @tonioros @nhdanh Sorry, but I really don't remember 😿

**Comment by CanWeb** [comment]
I have the same problem too ...

**Comment by dj-fiorex** [comment]
I reopen this, i have the same issues. table reload data only when i click a filter

**Comment by Chayuthh** [comment]
Me too I just add pagination when I change page the service work fine but table not updated, I need to move cursor around table, then data update.

**Comment by bharti112** [comment]
@Chayuthh @dj-fiorex @CanWeb  - Hey, I am facing the same issue, how did you manage to resolve it?
I am using ng2-smart-table 1.4.0 and Angular 7

**Comment by shinhwap** [comment]
@bharti112
Maybe you can try NgZone
Like `this.ngZone.run(() => this.source.load(this.excel[index].SheetData));`
