### ISSUE TITLE
nested json valuePrepareFunction

### ISSUE THREAD

**Issue by gesaleh** [akveo/ng2-smart-table#910]
I have a nested json 

`{
item: 1,
listi:[{id:1,p:2},{id:2,p:3},],
}`

I have the smart table loading but not listi i see it as objects i tried using 

` listi: {
        title: 'List elements',
        type: 'custom',
        valuePrepareFunction: (cell,row)  => {
          return row.listi.id
        },
      },
`
i get errors 

`ViewCellComponent.html:3 ERROR Error: No component factory found for undefined. Did you add it to @NgModule.entryComponents?`

i'm using ngx-admin so i have the following path` src/app/pages/tables/mytable/`

i tried several proposal i saw in issues but i might messed more things than fixing
any advice for this ?

**Comment by gesaleh** [comment]
I used the example for customRender to solve my issue thanks

**Comment by Thasli789** [comment]
columns: {
        project_code: {
          title: 'Project',
          type: 'html',
          filter: false,
          editor: {
            type: 'list',
            config: {
              list: []
            },
          },
          valuePrepareFunction: (value) => {
            for (let i = 0; i <= this.settings.columns.project_code.editor.config.list.length - 1; i++) {
              if(this.settings.columns.project_code.editor.config.list[i].value == value){
                return this.settings.columns.project_code.editor.config.list[i].title
              }
            }
          },
        },
      }
And then,
  getProject() {
    this.service.getProject()
      .subscribe(
        data => {
          this.settings.columns.project_code.editor.config.list = data;
          this.settings = Object.assign({}, this.settings);
        },
      )
  };

This is works for me🤗

**Comment by sobhardwaj** [comment]
anyone more on this to click perticular column

**Comment by Thasli789** [comment]
> ```
>   columns: {
>     project_code: {
>       title: 'Project',
>       type: 'html',
>       filter: false,
>       editor: {
>         type: 'list',
>         config: {
>           list: []
>         },
>       },
>       valuePrepareFunction: (value) => {
>         for (let i = 0; i <= this.settings.columns.project_code.editor.config.list.length - 1; i++) {
>           if(this.settings.columns.project_code.editor.config.list[i].value == value){
>             return this.settings.columns.project_code.editor.config.list[i].title
>           }
>         }
>       },
>     },
>   }
> ```
> 
> And then,
> getProject() {
> this.service.getProject()
> .subscribe(
> data => {
> this.settings.columns.project_code.editor.config.list = data;
> this.settings = Object.assign({}, this.settings);
> },
> )
> };
> 
> This is works for me🤗

**This is better way! 😊 Doesn't this work for you??? 😕**
