### ISSUE TITLE
How can I get reference of parent component inside onComponentInitFunction?

### ISSUE THREAD

**Issue by gunpal5** [akveo/ng2-smart-table#922]
Hello,

I am trying to create a custom component for action cell with dropdown menu. What I want to do is to process the menu item clicks in the parent component class.
`
onComponentInitFunction(instance) {
            instance.menuItems = [{name:'edit',title:"Edit"},{name:'delete',title:"Delete"}];
            //Require correct reference of 'this' here
            instance.menuItemClicked.subscribe(this.onActionItemClicked);
        }` 

Regards,
Gunpal Jain

**Comment by gunpal5** [comment]
Hello,

Please ignore it, I found the solution. this worked like this:
![image](https://user-images.githubusercontent.com/10114874/50377446-81b1cf00-0643-11e9-8da9-6d969093eaa9.png)

Thanks

**Comment by renanaribeiro** [comment]
Actually there is an error on docs...
You can call this function this way:

onComponentInitFunction: (instance) => {
    instance.click.subscribe(() => { this.openModal(); });
},

I was facing the same issue and found by [this reply](https://github.com/akveo/ng2-smart-table/issues/718#issuecomment-417271488)

**Comment by Alexsius-t** [comment]
> 
> 
> Actually there is an error on docs...
> You can call this function this way:
> 
> onComponentInitFunction: (instance) => {
> instance.click.subscribe(() => { this.openModal(); });
> },
> 
> I was facing the same issue and found by [this reply](https://github.com/akveo/ng2-smart-table/issues/718#issuecomment-417271488)

I don't know why exactly but using @gunpal5 solution i don't have "this is undefined" problem that i faced with your code.
