### ISSUE TITLE
Bug after pressing "esc" while inserting a new line.

### ISSUE THREAD

**Issue by gustavovitor** [akveo/ng2-smart-table#923]
Hello **everyone**.

The error is very simple to simulate, after click on "add" button, and get focus on new input on the line, if you press the esc key, all inputs are hidden, and don't not show more.

Has greater usability if the button run the cancel event on insert.

**Click on add button, move the cursor focus to input, and press esc..**
![image](https://user-images.githubusercontent.com/37344068/50386487-9be4bf00-06ce-11e9-9b50-754e35064d9b.png)

**After esc:**
![image](https://user-images.githubusercontent.com/37344068/50386490-c0d93200-06ce-11e9-8e9c-c6f5e607683e.png)

**Comment by gabriel-maus** [comment]
Have you found the solution? I have the same problem.

**Comment by gustavovitor** [comment]
No @gabriel-maus , I have migrated to ngx-datatable.
