### ISSUE TITLE
outputs

### ISSUE THREAD

**Issue by MeindertRomkes** [akveo/ng2-smart-table#93]
Hello,

I have the problem that all the outputs like (userRowSelect) & (edit) returns undefined. I cannot figure out how to solve this. Does anyone has a solution for me? 

Kind regards,
Meindert

**Comment by Tibing** [comment]
Hi @MeindertRomkes!
We will be happy to help you. Please, provide a bit more information about your environment and code.

**Comment by MeindertRomkes** [comment]
Sorry for the late response.  

My environment:
```
webpack version: 2.1.0-beta.22 (Angular CLI)
Webpack configuration is handled by angular cli, (more information)[https://github.com/angular/angular-cli]

typescript version 2.0.2

module version: latest of npm.

Environment: Ubuntu docker container.
```
I have this code in the component:

```
getOrders() {
    this.isRequesting = true;

    this.service.getOrdersFormatted('confirmed', true).subscribe(confirmedOrders => {
      this.source.load(confirmedOrders);
      this.isRequesting = false;
    });

    this.source.refresh();
}

selectOrder(data) {
    console.log(data);
  }
```

In the HTML:
```
<ng2-smart-table [settings]="settings" [source]="source" (userRowSelect)="selectOrder(data)"></ng2-smart-table>
```

**Comment by MeindertRomkes** [comment]
Oke I found the problem in my code. In the HTML I should have send the $event object instead of data. The html should be something like this:

```
<ng2-smart-table [settings]="settings" [source]="source" (userRowSelect)="selectOrder($event)"></ng2-smart-table>
```
