### ISSUE TITLE
Filters not working with paste

### ISSUE THREAD

**Issue by Platiplus** [akveo/ng2-smart-table#940]
When I copy data to apply some filters to a table and paste it before typing anything in to the column's filter box, the data isn't filtered.

If I type something on the filter box, erase it and paste it again, it works.

Steps to reproduce issue: go to ng2-smart-table main page, copy any value on the first row of the first table and try to paste it on the filter box above.

![screenshot_1](https://user-images.githubusercontent.com/1918291/51848425-b67d0a00-2304-11e9-9060-ee1f3fcc7ba2.png)

**Comment by sivkaneti** [comment]
Same here - @akveo-private any update on this one?

**Comment by prashanth517** [comment]
Is there any solution for this..I am trying to search by copy pasting the data ..its not getting filtered..

**Comment by medinam2m** [comment]
I'm having the same problem...
Any updates?

**Comment by shameerabdul** [comment]
Here too same problem. Any updates??

**Comment by prashanth517** [comment]
Did anyone have any solution for this??please help out

**Comment by sivkaneti** [comment]
seems that the new version 1.4.0 resolved the issue
