### ISSUE TITLE
Ng2 smart table pagination

### ISSUE THREAD

**Issue by mPishtra** [akveo/ng2-smart-table#960]
How do you handle pagination in ng2-smart-table in angular 7?
I have a too many records and it would take too much time to load all of them. How do i set the table to request 10 records at a time ?
For example: when the table loads for the first time is requests the 10 first records. When I press one of the pagination buttons, it requests the "n'th" records ? 
I've read the previous articles but I'm still unclear on how to handle this issue. 

Thank you

**Comment by revanthkolla** [comment]
Hi @mPishtra, did you get the solution? If so, could you please share the example.

**Comment by sharankasandula** [comment]
Use [ServerDataSource](https://akveo.github.io/ng2-smart-table/#/examples/populate-from-server)

**Comment by sunzhongshan1988** [comment]
No，you can't do it.

**Comment by mPishtra** [comment]
There was something that was clashing with the pagination. The guides provided by ng2-smart-table work.

Thank you

**Comment by georgetrad** [comment]
Check out my solution here:

https://stackoverflow.com/a/65583770/4306436

**Comment by shraddhahirve** [comment]
How did u solve this issue @mPishtra ?
