### ISSUE TITLE
setFilter - Multiple value on the same field

### ISSUE THREAD

**Issue by GazousGit** [akveo/ng2-smart-table#975]
Hello, I would like to know if there's a way to use the setFilter function and passing different values for the same field ?

I tried this way, but it doesn't seems to work (did I missed someting):

this.source.setFilter( [
        { field: 'user', search: 'admin' },
        { field: 'user', search: 'user' },
        { field: 'user', search: 'toto' }
      ]);

**Comment by benmed00** [comment]
You search three value in the same field, so it can't be done

**Comment by GazousGit** [comment]
True.
To solve this issue, I simply reload the table on a filtered data array with "user" I wanted to display.
